### ISSUE TITLE
CustomHidDevice (Error: Value is blocked)

### ISSUE THREAD

**Issue by dyroshan911** [Microsoft/Windows-universal-samples#1016]
I am using Universal Windows Platform sample CustomHidDeviceAcess to connect with my keyboard with HID support. But then I am getting the following error during 'Build'.

usage:0001 0006: Value is blocked, and not allowed on this bus 

Is there is no way to override it?

**Comment by oldnewthing** [comment]
I'll forward your question to the feature team. In the meantime, there is [a StackOverflow question(with answer)](https://stackoverflow.com/questions/42150814/universal-windows-platform-customhiddevice-error-value-is-blocked) on the same topic.

**Comment by oldnewthing** [comment]
Wait a second, the sample uses usage `FFAA 0001`, not `0001 0006`. It looks like you modified the sample. So this isn't a samples issue at all. The problem is with your modifications to the sample.

You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
