### ISSUE TITLE
Providing Item Source for multiple POI on map using grid without MapItemsControl.

### ISSUE THREAD

**Issue by TUSHAR94** [Microsoft/Windows-universal-samples#1026]
> 
> This example is work correctly on 2d map:
> 
> ```
> <Maps:MapControl 
>     Center="{Binding MapCenter, Mode=TwoWay}"
>     <Grid 
>         Maps:MapControl.Location="{Binding MapCenter}"
>         Maps:MapControl.NormalizedAnchorPoint="0.5,1">
>         <Image Source="/Assets/Images/GeoPointerA.png"></Image>
>     </Grid>
>  </Maps:MapControl>
> ```
> Why NormalizedAnchorPoint don't work with MapItemsControl? Is it bug?

How can i provide collection to this grid? It is working for single Image but when i have to show multiple i am unable to provide ItemSource.

_Originally posted by @TUSHAR94 in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ0MzYyNjgzNg==/timeline/issue_comment#issuecomment-443626836_

**Comment by oldnewthing** [comment]
This does not appear to be a question about a sample in this repo. (That XAML fragment you posted does not exist in this repo as far as I can tell.) If this is a question about the MapControl itself rather than about the MapControl sample, then you can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
