### ISSUE TITLE
HolographicFaceTracker multi run crash

### ISSUE THREAD

**Issue by wosborn** [microsoft/Windows-universal-samples#1038]
After a successful build and deploy of HolographicFaceTracking app to a HoloLens, any subsequent runs from clicking the actual app tile either freeze on load or crash back to the floating app window hologram. Has anyone else seen this issue? Is something possibly not getting shutdown properly on close?

I am at    commit ad21b9c1ff2e619081343

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by yl-msft** [comment]
@wosborn the problem you are seeing is typically due to app not properly handling pause and resume on hololens.   You can in the shall to close the app tile and relaunch it from the start menu.

This sample is meant to demo the code for the APIs on the cameras, so it's not paying attention to other pieces.
