### ISSUE TITLE
Direct2d & emotion

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#1040]
UWP TextBlock control draws "&#128549" to &#128549;   , how to draw this string to emotion in Direct2d?
I have tried passing the string to CreateTextLayout ( D2D1_DRAW_TEXT_OPTIONS_ENABLE_COLOR_FONT is set), but it does not work. 

passing U+1F625 not work either.

![image](https://user-images.githubusercontent.com/12285582/50570854-9de90500-0dd5-11e9-9f5e-af58e6ef7541.png)
passing text like the pic above works, but the string I get from server is like "&#128549", how to draw this string into emotion?

[https://docs.microsoft.com/en-us/windows/desktop/DirectWrite/what-s-new-in-directwrite-for-windows-8-consumer-preview#whats-new-in-windows-8](url)
"Starting with Windows 8, DirectWrite supports the Unicode codeblock associated with emoji, so if your app uses the Unicode standard codepoints for emoji it displays the appropriate glyphs."

Happy New Year!

**Comment by oldnewthing** [comment]
This appears to be a question about Direct2D rather than a question about the sample itself. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
