### ISSUE TITLE
The Casting Smaple always cast the desktop instead of the video

### ISSUE THREAD

**Issue by CobraCalle** [Microsoft/Windows-universal-samples#1062]
Hello,

when I try the samples, it casts always the desktop to the other device… am I doint something wrong or is this a bug?

Thanks

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Feature team tells me that this is by design. Miracast is always mirror mode. Casting to a DLNA device lets you be more specific, but Miracast is whole-screen.

**Comment by CobraCalle** [comment]
...so creating a casting connection and set a source of type video / image results in mirroring the sceen is the correct behavior?

I don't think so... even the "Basic Media Casting Sample" does not work… myTube! from Windows store starts mirroring the screen to when you start casting a video from the app.

What I want to do:
1. Search all devices that can show images
2. Create a connection
3. Set an image source

Expected result: I can see the image on the other screen
Result: I starts mirroring the desktop

How could this be the correct behavior?

**Comment by CobraCalle** [comment]
To be absolute specific:

1. Run the Basic Casting Sample
2. Load a video
3. Click on cast
4. Select a device that supports video playback (MS Wireless Display Adapter and Connect App on another mchine tested)

Expected result:
I can watch the video on the other screen

Result:
It starts mirroring the desktop

Not 100% sure, but I think this has been working (casting videos with myTube! to an other device)

**Comment by CobraCalle** [comment]
Now I've tried it with a Samsung TV (shows DLNA on device list)… same result… instead of playing the video / showing the image, windows mirrors the desktop to the TV

**Comment by CobraCalle** [comment]
….btw. I have tested this on three different machines:

1. newly setup workstation (just Windows, Drivers and VS)
2. another Workstation
3. A Surface Book with Skip Ahead

The problem is on all three machines…

**Comment by oldnewthing** [comment]
Feature team says that DLNA does not support screen mirroring; it only shares content. Samsung TVs support both Miracast and DLNA, so it's possible that the connection is being done as Miracast instead of DLNA, and that would result in screen mirroring. Feature team suggests the following experiment:

* Use the DLNA receiver scenario in the Advanced Casting sample.
* Set up Windows Media Player as a DLNA receiver:
    1. Open Windows Media Player.
    2. Stream -> Allow Remote Control of my media player.
* Wait for the "<device name> (Windows Media Player)" to show up in the device picker/casting app. 
* Cast to it.

The feature team tested Casting with the Movies&TV App and it operated as expected.
