### ISSUE TITLE
Visual Basic?

### ISSUE THREAD

**Issue by hannespreishuber** [Microsoft/Windows-universal-samples#110]
does Visual Basic not longer exists?

pls submit VB sample code

**Comment by Padanian** [comment]
You can convert c# code to vb code online, like here http://converter.telerik.com/

**Comment by CageySea** [comment]
@Padanian sorry that suggestion is no help. The issue is not with writing or converting code. The issue is things like declarations, scoping variables and so on. I would like to see a working sample app in VB, so that I can see how everything gets wired together. Even one "hello world" type sample would let us get started. At the moment there is absolutely nothing. I want to start writing an app, and would prefer not to write it as an 8.1 or WinForms app and have to convert it later, but at the moment I don't seem to have any option.

**Comment by hannespreishuber** [comment]
@Padanian every VB.NET dev know the conversion sites as of the missing code samples.

**Comment by Padanian** [comment]
Can't see your point. But I perfectly see the annoying assertive German style in hannespreishuber messages.

**Comment by AnthonyDGreen** [comment]
Hey @hannespreishuber, @CageySea,

My team, the VB team, has been working on translating, reviewing, and testing the samples for VB for a few weeks now. I think there are about 150 of them and it's taken longer than we'd hoped but we hope to publish the first batch this week. Apologies for the delay.

**Comment by CageySea** [comment]
Thanks @AnthonyDGreen I'm looking forward to seeing them and itching to get started on my own little project!

**Comment by CageySea** [comment]
@AnthonyDGreen that week for the first batch seems to be taking a long time. Any news on when we can expect to see something?

**Comment by AnthonyDGreen** [comment]
@CageySea,

Sorry for the delays. I've been out for the last couple of weeks. I won't bore you with the adventure but the short story is that Win10 Universal is a much different beat than the traditional desktop app and the translation tools we have weren't even remotely prepared to analyze Win10 projects. Tried to do a syntactic conversion but the volume of conversion errors produced by translation was daunting (if not untenable). On top of that there was a change in how the samples are set up that happened since this all started which reset the entire process. The conversion process has matured considerably in the last month. It's still far from automatic but it's at least repeatable to a point. Today's my first day back in the office so I can't give you another estimate on when the VB samples will go live but it does seem like we're at the "light at the end of the tunnel" phase.

**Comment by JasonRosenthal** [comment]
Any news on VB?  I finally solved many of the VS 2015 installation bugs and I'm ready start doing some Windows 10 stuff.  I hope the trouble in translation is not due to the Visual Studio team adding features to C# and neglecting VB.  With native complie, this version of Visual Studio could be as ground breaking as VB5 when it introduced the feature. (QuickBasic before that).  Hopefully we'll get the samples before we switch back to p-code again. :)

**Comment by AnthonyDGreen** [comment]
@JasonRosenthal, I expect the first batch of VB samples to be submitted to our staging repo today. It only represents ~20% of the .NET samples (33 samples). Fortunately most (but now all) of the kinks have been worked out of the conversion process so that the average time to manually inspect and correct any translation errors is manageable so remaining batches won't take nearly as long as this first one. The are a handful of samples so far which do rely on features that don't exist in VB - mainly unsafe code in some of the communications samples that deal in memory buffers.

**Comment by oldnewthing** [comment]
VB samples are entering the pipeline now. Should be in the next refresh (v1.0.8).

**Comment by oldnewthing** [comment]
The first round of VB samples arrived in v1.0.8. Thanks for your patience. More to come.

**Comment by bvillersjr** [comment]
Sadly, many examples here, if not most, still neglect VB.Net devs. Most all seem to support C# where possible. IN many cases we see JS and other non Microsoft languages being supported before VB.Net. Across the board it seems Microsoft is investing more heavily in winning over devs from other ecosystems than they are in keeping the devs they have form the VB.Net ecosystem. If you're a C# dev / employee at Microsoft and you think that VB.Net devs are OK with this, accustomed to having to translate C# to VB.Net, etc.., you are sorely mistaken. I've come to the point that the neglect of VB.Net is forcing me to change languages. VB.Net devs have been severely mislead and frankly shafted by Microsoft in many ways despite many promises that this would never happen. As a result, I must learn from my mistakes and never again drink the Microsoft Kool-Aide so to speak . Therefore I cannot view C# or any Microsoft specific languages as viable options for the new language I'm being forced to learn. 

I sincerely hope that this neglect winds up being worth it and that you guys gain more devs of the non-Microsoft languages than you're losing in VB.Net devs who are wising up and refusing to buy more Microsoft storyline. From here on out, if a language isn't vendor agnostic, it won't be part of my vocabulary.

Best of luck

**Comment by Padanian** [comment]
I have to agree ot every last word of bvillersjr's'rant.
