### ISSUE TITLE
I cannot debug Cortana App

### ISSUE THREAD

**Issue by jasuperior** [Microsoft/Windows-universal-samples#113]
I just downloaded this package today, and when trying to test out the included cortana app (JS), selected x64 as my target cpu, and hit debug on my "local machine", i get the following error: 

"the debugger cannot continue running the process. unable to start debugging"

What should i do?

**Comment by oldnewthing** [comment]
This is a problem with Visual Studio.

**Comment by oldnewthing** [comment]
I took a brand new machine, installed Windows 10, then installed Visual Studio (include Web development tools, included by default I think). So this is not a problem with the samples; it's a problem with Visual Studio. Maybe you can ask on a Visual Studio forum.

**Comment by xuchen** [comment]
i was able to debug it too, with brand new windows 10 and Cortana.

However, I couldn't figure out a way to change the relative references to "Microsoft.WinJS.4.0". Say I copied one project out of the sample folder, and wanted to have my own project in another folder. The new project doesn't compile because the link to "Microsoft.WinJS.4.0" has changed. But how do I fix it?? I couldn't find a config option from VS 2015. The "Microsoft.WinJS.4.0" folder is full of "placeholder" files.

**Comment by oldnewthing** [comment]
It sounds like you unzipped just one sample instead of unzipping the entire repo. As noted in the instructions, you have to unzip the entire repo because of cross-references to shared content (such as Microsoft.WinJS).

**Comment by oldnewthing** [comment]
You cannot copy the sample project to another solution. The sample projects are linked to other parts of the repo, as noted in the README. Furthermore, copying the project does not regenerate things that are supposed to be unique (like project GUIDs). If you want a private copy of a project, create a new project from the Visual Studio "New Project" menu, then copy/paste the code from the original project that you want to put into the new project.

**Comment by xuchen** [comment]
Got it!Thanks! I just got stuck with how-to-unlink-the-shared-content part in VS 2015. I ended up creating a brand new project.
