### ISSUE TITLE
Camera has low FPS on HoloLens2

### ISSUE THREAD

**Issue by jianchong-chen** [microsoft/Windows-universal-samples#1163]
I used the FindCameraDeviceByPanelAsync to get MediaFrameSourceGroup and then initial with MediaCapture to get the camera steam. The whole steps are the same as [here](https://docs.microsoft.com/zh-cn/windows/uwp/audio-video-camera/use-opencv-with-mediaframereader).
It's running ok on Hololens 1, while has low FPS(~6FPS) on Hololens 2.
I read the sample code of [CameraGetPreviewFrame](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/CameraGetPreviewFrame), and found it's a little different about opening camera.
Should I update my code to get higher FPS on Hololens2?

**Comment by oldnewthing** [comment]
This appears to be a platform issue rather than a sample issue. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
