### ISSUE TITLE
Compilation in the sample LockScreenApps

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/Windows-universal-samples#1195]
In my work project, I have the same error that is happening in the LockScreenApps project:

error 80080204: App manifest validation error: Line 45, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint=

This bug appeared in the past too: https://github.com/Microsoft/Windows-universal-samples/issues/925

The workaround of changing the target version is a no go for my work project. Fun fact: my project does not compile after refactoring the project name.

Thanks

**Comment by oldnewthing** [comment]
This appears to be a question about your app, not a question about the LockScreenApps sample. (From what I understand, the LockScreenApps is basically relying on a bug in the old manifest validator, which is why rolling back "fixes" the problem. The problem is not actually fixed. It's just that the validator doesn't notice.)

You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options for your app. (Click "Forums and community".)
