### ISSUE TITLE
Systray sample or tutorials.

### ISSUE THREAD

**Issue by catafest** [microsoft/Windows-universal-samples#1201]
It will be great if the development team will provide a **systray example with C# and UWP**
or tutorials, video tutorials, or reference books.
Thank you. Best regards.

**Comment by oldnewthing** [comment]
[SystemTray](https://docs.microsoft.com/en-us/previous-versions/windows/apps/ff626537(v=vs.105)) is an old feature from Windows Phone. Since Windows Phone has been discontinued, there is not much value in having a sample for a discontinued product.

**Comment by catafest** [comment]
I want to solve my problem with Windows 10 - System Tray https://www.tutorialspoint.com/windows10/windows10_system_tray.htm

**Comment by oldnewthing** [comment]
Oh, that's call the Notification Area. The System Tray was the strip at the top of the screen on Windows Phone. I do not believe there's a UWP API for the notification area, probably because not all UWP platforms have a notification area in the first place. (Desktop is basically the only one. Xbox doesn't have one, Hub doesn't, Phone didn't. And even Desktop doesn't have one when in Tablet Mode.)
