### ISSUE TITLE
UWP app using AudioGraph recording is being suspend during record

### ISSUE THREAD

**Issue by gustavohansen** [microsoft/Windows-universal-samples#1223]
Hi, Im running an app that needs to record audio. I notice when i minimize the app, its being suspended. This produced the AudioGraph recording to stop. 

Do know how to prevent this?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

UWP applications which need to continue to run when minimized can use Extended Execution.

**Comment by Zofware** [comment]
Having run into an issue like this myself and being baffled by it for a few weeks, I'd like to drop a hint to @gustavohansen. To prevent this you need to declare the ` backgroundMediaRecording` capability for your app. It's a restricted capability so the process for declaring it is a bit involved. The details are [here](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities).

Honestly, since these samples are meant to be instructional and to show best practices, I really believe the readme for this sample should include a short note about this.
