### ISSUE TITLE
Delay when call SpeechRecognizer.RecognizeAsync Method after 30 seconds between 2 calls

### ISSUE THREAD

**Issue by nicolamanes** [microsoft/Windows-universal-samples#1307]
**Which sample are you reporting a bug in?**

https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognizer.recognizeasync?view=winrt-20348

Example: ResizeAppView

**Describe the bug**
It's a SIMPLE QUESTION:
When i call the method SpeechRecognizer.RecognizeAsync several time in any application it works well and is reactive.
if i wait i.e. 30 secs and call again the method the recognizer starts with a delay let's say between 500 to 1000 ms

**To Reproduce**
is related to a Method Call

**Expected behavior**
Execution time. it seams that the Recognizer is set to sleep by the OS...

**Screenshots**
not applicable

**Configuration**
C#/Windows 10

**Additional context**

Thank you for your help
Nicola

**Comment by oldnewthing** [comment]
It looks like your issue is not with the sample in this repo, but with the feature itself. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
