### ISSUE TITLE
AppUiBasics sample can't build

### ISSUE THREAD

**Issue by jerrak0s** [Microsoft/Windows-universal-samples#133]
I can't build AppUiBasics. I just downloaded the latest version of samples, but i get many errors while i try to rebuild or deploy sample AppUiBasics.

**Comment by RuslanSCH** [comment]
Hi jerrak0s! Can u tell me, you deploy it on Local Machine or an Device?

Since this morning i cant debug my apps (and all this sample's). VS can't deploy it on any mobile Device, such my Lumia 640 (10512 build) or WindowsPhoneEmulator. Have no syntax errors or any other troubles, 

I have repared my VS2015 CommunityEdition and tried to Run an BlanckApp on an ARM Device ( Lumia 640), and Deploy Error is still here.

**Comment by jerrak0s** [comment]
I deploy/rebuild it on Local Machine. I get some errors for the assets like 

```Could not copy the file "C:\Users\me\SharedContent\media\Samples\grapes.jpg" because it was not found.AppUIBasics```

**Comment by RuslanSCH** [comment]
Thx, this is not a same issue...

**Comment by AdamBraden** [comment]
jerrak - the samples use linked files to minimize diskspace.  Please verify you downloaded the entire repo and the SharedContent folder with its content exists.

Ruslan - if you cannot deploy a blank app, Post your detailed steps and error information on the main development forum to help debug your environment:
https://social.msdn.microsoft.com/Forums/en-US/home?forum=wpdevelop

**Comment by RuslanSCH** [comment]
@AdamBraden  Thank you Adam , but after re-install VS and all update's it is working again

**Comment by jerrak0s** [comment]
@AdamBraden ok that it was.
