### ISSUE TITLE
Application registration unsuccessful: Error 0x80070005. Unable to open file from position: Appxmanifest.xml. Error: Access denied

### ISSUE THREAD

**Issue by Padanian** [Microsoft/Windows-universal-samples#135]
What exactly is the above message referring to?
I tried to run the example StreamSocket, without success.
I forked this repo in my repo, and connected visual studio 2015 to it.
I edited the package.appxmanifest to reflect my setup, all to no avail.

**Comment by DavidGoll** [comment]
Which language were you trying? Were you trying to run locally or on a device?

**Comment by Padanian** [comment]
C#.
Locally, both x86 and x64 fail with the same error.

**Comment by AdamBraden** [comment]
VS 2015 RTM overwrites any values you place in the package.appxmanifest with what you specify in the Project Properties targets.  If you have VS2015 RTM with the Win10 SDK & tools installed, you should not need to change anything in the sample.

Please confirm if you can create a new blank UWP project. If not, you should post your question to the main forum to get help debugging your environment.
https://social.msdn.microsoft.com/Forums/en-US/home?forum=wpdevelop

**Comment by Padanian** [comment]
I confirm I have VS2015 Enterprise and win10sdk installed.
Whether package.appxmanifest is pristine or edited doesn't make a difference.
I can create a blank UWP with no issues at all.
Does my locale have any undesired effect on the package.appxmanifest?
And why does VS complain about Appxmanifest.xml? There is no such file in the package. 
The file is package.appxmanifest

**Comment by Padanian** [comment]
solved: I had to give full rights to the SYSTEM account to the folder with the source code and renamed package.appxmanifest to appxmanifest.xml

**Comment by AdamBraden** [comment]
FWIW - When you do a "build" it should create an appxmanifest.xml file for you in the \bin folder based on the package.appxmanifest in your project. 
 
I'm curious if you cloned the repo or downloaded the zip file and what folder you installed to.  if the problem is VS or some process it spawns doesn't have access, you might try running VS as admin and see if that solved the problem.

**Comment by Padanian** [comment]
I forked the repo and imported it via Visual Studio Github built-in function.
My home for repos is c:\users\<user>\Documents\Visual Studio 2015\Repos which is actually a NTFS junction to another drive containing the folder. Only me got permissions on that folder until now. I had to give full rights permissions to user SYSTEM, which is reasonable considered it has got to build and copy some files.

**Comment by aptly-io** [comment]
@Padanian I had the same issue and it might still be there.

Cloned the repo, could deploy the sample Nfc (within the repo directory structure) without issues. 

Then copied the SharedContent and Nfc subdirectories into another location for making a separate prototype. Deploy failed and I looked almost a whole day find the cause until google brought me to this issue thread.

There's something wrong with the file permissions on some directories causing the SYSTEM to not have permission on these subdirectories. Trying to change the permissions through the Explorer (got a warning that the order of permissions was incorrect) made things only worse.

Finally I got a tar.gz archive instead of a clone from GitHub, this way I could copy out these subdirectories and deploy without issues.

**Comment by empjustine** [comment]
```
VERBOSE: Performing the operation "Register package" on target "H:\abc\cde\appxmanifest.xml".
Add-AppxPackage : Deployment failed with HRESULT: 0x80070005, Access is denied.

error 0x80070005: Opening file from location: appxmanifest.xml failed with error: Access is denied.
```

Can confirm from empyrical evidence that this issue is caused by the missing ACL entries on files and folders ammong the `appxmanifest.xml` path.

Had to create a new text file with a working ACL and replace the ACL of everything in the path to get this working again.
```powershell
$NewAcl = Get-Acl "C:\Users\empjustine\Downloads\New Text File.txt"
Get-Item -Path "H:\abc\" | Set-Acl -AclObject $NewAcl
Get-ChildItem -Path "H:\abc\" -Recurse -Force | Set-Acl -AclObject $NewAcl
```

**Comment by bedrin** [comment]
Worked for me only after I've checked "Replace all child object permission entries with inheritable permission entries from this object" checkbox when I was granting "Full control" to SYSTEM user
