### ISSUE TITLE
AssociationLaunching example doesn't work for .zip files on Windows 11 Pro 22H2

### ISSUE THREAD

**Issue by nesbox** [microsoft/Windows-universal-samples#1367]
Example: AssociationLaunching

1. Open `Package.appxmanifest`, go to the Declarations tab and add `.zip` file extension
2. Build and run the example
3. Try to open any `.zip` file using the explorer context menu
4. `No such interface is supported` error message appears ![image](https://user-images.githubusercontent.com/1101448/193279820-d4a663ad-f5a3-4eff-b1e9-3361a74e8b13.png)

Interestingly, all other file extensions work well, the problem is only with `.zip` and only on Windows 11 Pro 22H2.

**Comment by ValeraFinebits** [comment]
Additional info
Here's a link to Feedback Hub: https://aka.ms/AAi9ln6

We’re reaching out to notify you of an issue in Windows 11 Version 22H2. The problem relates to archives opening by association. I want to draw your attention to the fact that this problem is also observed in other UWP applications (9Zip, Rar Zip Extractor Pro, etc.) and only in version 22H2.

The issue details are below. 

An error message is observed when opening an archive with 8 Zip by association (.zip)

Note: Issue is observed in other UWP apps. On Windows 11 version 21H2, the error is not observed.

OS: Windows 11 Pro Version 22H2 Build 22621.521

Applications: 8Zip Pro version 1.4.42.0, 8Zip version 1.4.40.0

Repro steps:

1. Install 8 Zip app from the Microsoft store.

2. Open the folder with the archive in Files Explorer.

3. Call the context menu on the archive file (.zip).

4. Select "Open with".

5. Select 8 Zip app.

6. Observe.

Actual Results: An error message is observed (see attachment).

Expected Results: Application 8 Zip opens the selected archive without errors.

**Comment by AdamBraden** [comment]
@kanismohammed - are you aware of an issue in this area or can have someone investigate?

**Comment by oldnewthing** [comment]
This repo is for the samples, not for the underlying OS functionality that supports them. This problem appears to be in the underlying functionality; there is no bug in the sample itself. If you feel that this is a sample bug, please elaborate.

**Comment by ValeraFinebits** [comment]
Yes, there is a bug in Windows 11.  @oldnewthing could you call someone from the appropriate team here to fix this bug?

**Comment by ValeraFinebits** [comment]
> This repo is for the samples, not for the underlying OS functionality that supports them. This problem appears to be in the underlying functionality; there is no bug in the sample itself. If you feel that this is a sample bug, please elaborate.

@oldnewthing Please give me a link to the correct repo so I can file this bug.

**Comment by oldnewthing** [comment]
@ValeraFinebits You report OS bugs via Feedback Hub. The team tells me that they received your report and are investigating.

**Comment by AdamBraden** [comment]
@ValeraFinebits - We've routed the fbhub bug to the feature team. Can't guarantee when the team can look at it, but you can track progress there.
thx

**Comment by ValeraFinebits** [comment]
@oldnewthing thank you for your help. I'll be asking you here from time to time how is going work on fixing this bug, because the report to the Feedback Hub was sent in June 2022.

**Comment by ValeraFinebits** [comment]
Hi, @oldnewthing in Win11 23H2 bug still live. Could you please help?

**Comment by oldnewthing** [comment]
@ValeraFinebits As I noted, this repo is not for product bugs. This is a samples repo. I cannot help with product issues.

**Comment by ValeraFinebits** [comment]
> @ValeraFinebits As I noted, this repo is not for product bugs. This is a samples repo. I cannot help with product issues.

@oldnewthing 
I understand. But what can I do to get the bug fixed? 
The bug was reported back in 2022, and you said that it reached the responsible team

**Comment by ValeraFinebits** [comment]
> @ValeraFinebits As I noted, this repo is not for product bugs. This is a samples repo. I cannot help with product issues.

@oldnewthing 
Do you suggest voting for this issue on GitHub? Because there's no way to vote for my review in the Feedback Hub.

Additional Information in Win11 23H2 the same problem was added to .7z files. Now, it is obvious that the problem is related to .zip and .7z support in Explorer. It's good that Microsoft adds features to Explorer, but why break UWP archivers from the Store?

**Comment by oldnewthing** [comment]
The feature team doesn't monitor this github issue.

**Comment by ValeraFinebits** [comment]
> The feature team doesn't monitor this github issue.

@oldnewthing 
I ask you to help me find the right place so that the feature team can see this problem.

**Comment by oldnewthing** [comment]
My only guess was the Feedback Hub issue. I don't know the feature team personally, so I don't know what mechanism they use to "plus one" a bug report.

**Comment by AdamBraden** [comment]
fyi - the feedback hub issue is marked as fixed in WIP-Canary. Its making its way through servicing channels on Win11 which will take a couple months

**Comment by ValeraFinebits** [comment]
> fyi - the feedback hub issue is marked as fixed in WIP-Canary. Its making its way through servicing channels on Win11 which will take a couple months

Thank you.
