### ISSUE TITLE
Cortana AdventureWorks Javascript code finished?

### ISSUE THREAD

**Issue by xuchen** [Microsoft/Windows-universal-samples#144]
Just want to check out the status of this code. The following webpage clearly didn't finish:

https://msdn.microsoft.com/en-us/library/windows/apps/dn974229.aspx

It looks like a simple copy of the c# version. I wonder whether the sample `CortanaVoiceCommand/js` projects supports the **background** app as stated in the above webpage?

**Comment by anpilley** [comment]
Hi xuchen. The javascript sample doesn't require a separate background project to implement the background task that a c# or c++/cx does. See the file https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/CortanaVoiceCommand/js/AdventureWorks/js/voiceCommandService.js

**Comment by xuchen** [comment]
Thanks! It would be nice if someone could finish the MSDN documentation, otherwise it's a bit confusing.

Question from a first time VS user: the project links to `Microsoft.WinJS.4.0`, which is a relative link to `../SharedContent/js/Microsoft.WinJS`. How do I change this relative link path? I copied the project to someplace else for a new project, but couldn't get the references right no matter how.

**Comment by anpilley** [comment]
I'll pass along a reminder to the documentation team that the JS sample is available and that the docs should be updated, I'm not sure how that got missed, although I know the documentation team was very busy around the time that sample became available, I was unfortunately on vacation shortly after the sample got finished, and that must have been missed as a result.

I wouldn't really recommend taking our samples and trying to modify them directly into your own apps. There's a number of features and customizations that VS makes when you create a new project that won't happen that way, including unique guids that help identify your app in the store, and the samples aren't necessarily going to get accepted to the store in their current state (by design), leading to headaches for you to resolve.

You'll be better served starting with a brand new project, since that will set up the WinJS references correctly for your project. You can copy the files and change the <Content> tags in the jsproj if you want, but if newer SDK versions come out in the future and you want to update them, you may run into all sorts of unanticipated issues.

For the winjs references, you just need normal <Content Includes="path/to/file.js" /> references like any other JS file in a winjs project, so move the file, update the jsproj to reflect the new location of the file, and remove the <Link> tag for that file.

**Comment by xuchen** [comment]
Thanks!! I ended up creating a new project from scratch as you suggested.

If I may add another example please, from the `CortanaVoiceCommand` project: I want to know what user said exactly when matching command, thus in the VCD file I used a wild card:

    <Command Name="wildCardCatchAll">
      <ListenFor>{*} </ListenFor>
      <Feedback>OK, I heard you!</Feedback>
      <VoiceCommandService Target="VoiceCommandService"/>
    </Command>

However, the matched {*} wasn't passed to the app service. When I got the voice command from `getVoiceCommandAsync()`, the voice command's `speechRecognitionResult.text` field only contains `...` (the VCD file [definition](https://msdn.microsoft.com/en-us/library/dn706593.aspx) seems to confirm this). So the question is: how do I get the full text command? I saw Cortana recognized it, but the text simply wasn't passed to my program.

**Comment by anpilley** [comment]
What you want is to use a PhraseTopic. I've discussed that on the MSDN forums [here](https://social.msdn.microsoft.com/Forums/en-US/9e24460d-8114-4d72-a0f2-0c024f4a61e6/uwp-xaml-cortana-commands-with-wildcard-support?forum=wpdevelop), you might want to take a look into that.

**Comment by xuchen** [comment]
Got it! Just got it working! Thanks! I'll move to the forum for further questions like this!
