### ISSUE TITLE
Background transfer sample doesn't work on HP Elitepad 1000 G2

### ISSUE THREAD

**Issue by terry-dai** [Microsoft/Windows-universal-samples#157]
Works fine on my Windows 10 x64 (build 10240) laptop.

But when running on HP ElitePad1000 (upgrated to windows 10), download hangs on following line:
await download.StartAsync().AsTask(cts.Token, progressCallback);
in file Scenario1_Download.xaml.cs

**Comment by DavidGoll** [comment]
This issue is not actionable as we cannot reproduce. Also, this is not an issue with the sample per se.

If this issue is continuing to happen, you can open a support case with our Developer Support team:
 
1. Visit [http://aka.ms/storesupport](http://aka.ms/storesupport) and sign-in with your Microsoft account
1. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
