### ISSUE TITLE
LockScreenApps sample ScenarioInput1 doesn't work as described

### ISSUE THREAD

**Issue by floydfix** [Microsoft/Windows-universal-samples#163]
"There are only 7 lock screen slots and an app may request to fill a single one of these. Of these seven apps, one may also take the detailed status slot on the lock screen. If the user declines to give your app permission, you may not prompt again. Apps can query the current state of the setting and may prompt the user a single time to see if they want to allow the app to appear on their lock screen.  Subsequent attempts to prompt the user will result in returning the app's current status, without showing any UI to the user."

When I install this sample on my Lumia 630 and click the button to request to be put on the lock screen, the application is allowed access, but nothing is placed onto the lock screen without manually going into the lock screen settings of the phone and adding the application to one of the empty slots.
Is there no programmatic way to get an application added to the lock screen? I was hoping that this is what was meant by the description listed above.

**Comment by anbare** [comment]
The behavior of the lock screen prompt and requirements has changed in Windows 10. Calling `BackgroundExecutionManager.RequestAccessAsync` will no longer prompt for placing your app on the lock screen, since being on the lock screen is not necessary for you to have background tasks anymore (this is the same behavior as Windows Phone 8.1, it was only Windows 8.1 that prompted to add to lock screen when calling that method). The [MSDN documentation](https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.background.backgroundexecutionmanager.requestaccessasync.aspx) somewhat explains this (though it's poorly worded and still confusing).

You can launch the settings app into the lock screen settings if you'd like to help users discover how to enable the lock screen. To do that, you'd use the [URI schemes for the Settings app], like seen below...

    await Launcher.LaunchUriAsync(new Uri("ms-settings:lockscreen"));

This sample hasn't been updated for Windows 10 yet, hence the false information in the sample. We'll get someone to update it. Thanks for bringing up this issue!

**Comment by corywink** [comment]
The sample has now been updated for Windows 10.
