### ISSUE TITLE
Bug in Drag&Drop when navigating back from webview page

### ISSUE THREAD

**Issue by ibosong** [Microsoft/Windows-universal-samples#196]
The Drag&Drop events on the target control (such as DragOver, Drop...) will disappear when navigating back from a page which includes WebView control.

I would like report this bug here for someone who will encounter this problem.

And my solution is creating a new WebView at background thread in the code-behind:

``` c#
WebView web = new WebView(WebViewExecutionMode.SeparateThread);
```

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the drag/drop sample in this repo (because the XamlDragDrop sample doesn't use a WebView). You can open a support case with our Developer Support team to report platform issues:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
