### ISSUE TITLE
KeyCredentialManager sample exception

### ISSUE THREAD

**Issue by suprak** [Microsoft/Windows-universal-samples#197]
When trying to use the KeyCredentialManager sample, the code throws,
>System.AccessViolationException was unhandled by user code
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Windows
  StackTrace:
       at Windows.Security.Credentials.KeyCredential.GetAttestationAsync()
       at SDKTemplate.SignIn.<CreatePassportKey>d__16.MoveNext()
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  InnerException:

Line 340 in SignIn.xaml.cs
```CS
KeyCredentialAttestationResult keyAttestationResult = await userKey.GetAttestationAsync();
```

**Comment by msftchcamp** [comment]
suprak, sounds like you will need the new Windows 10 UAP SDK included with Visual Studio Update 1 (the new SDK version is 10586 while the old one is 10240).

You can find the update details here: http://blogs.msdn.com/b/visualstudio/archive/2015/11/30/visual-studio-update-1-rtm.aspx and you can download the update using the first link with the text "Visual Studio Update 1". 

After you do that you will need to change the version of UAP the sample is targeting to be 10586 instead of 10240 by going into the project properties. After that the sample will work!
