### ISSUE TITLE
VoIP - sending messages from background to foreground

### ISSUE THREAD

**Issue by mbencer** [Microsoft/Windows-universal-samples#202]
Hello!
I'm working on VoIP application projects. My research show that the only possibility to send messages from background (AppService) to GUI (foreground) is asking App Service for response. It causes that I have to create thread with loop in GUI which ask for response for example every 1 s - it consume some CPU. Have somebody any ideas how to send messages from App Service to GUI without asking ?

**Comment by dpierangeli** [comment]
For a generic background task the foreground app can register to progress events, maybe is possible also for the app service.

https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/monitor-background-task-progress-and-completion

**Comment by lstachowicz** [comment]
Hi,

There is possible to make 2 way communication here is brief sample:

**In Background App**
In Function `Run(IBackgroundTaskInstance taskInstance)` in AppService save connection:
```
AppServiceTriggerDetails triggerDetail = taskInstance.TriggerDetails as AppServiceTriggerDetails;
connection = triggerDetail.AppServiceConnection;
```

Now you can use connection to send message from background to foreground by:
`connection.SendMessageAsync(ValueSet value)`

**In Foreground App**
When you opening `AppServiceConnection` register also callback for `RequestReceived` in the same way as `ServiceClosed` in order to get message from Background.

Check also Channel9:
https://channel9.msdn.com/Events/Windows/Developers-Guide-to-Windows-10-RTM/Application-Services

**Comment by mbencer** [comment]
Hi,
Thanks Łukasz for answer ;)

Best regards,
Mateusz Bencer
