### ISSUE TITLE
Sample request for creating custom lock screen with Windows.ApplicationModel.LockScreen

### ISSUE THREAD

**Issue by pingzing** [Microsoft/Windows-universal-samples#239]
According to the MSDN documentation, with the Windows.ApplicationModel.LockScreen classes, "You can create an app that acts as the lock screen, allowing greater user personalization", but there's no further information.
Could we get a sample demonstrating this or, alternately, have the MSDN documentation clarified to indicate that these APIs are only for use with things like kiosk apps?
For reference, my interest is in creating replacement lock screens for Windows 10 Mobile, which the various classes in this namespace seem to be intended for.

**Comment by oldnewthing** [comment]
Yes, this is for kiosk scenarios. The good news is that a lock screen sample is in the works. Sorry it's taking so long. The bad news is that the LockScreen namespace is supported only on Desktop right now, so it won't help you.

**Comment by Sweex** [comment]
So that means that we won't be able to develope lockscreen apps for Windows 10 Mobile? Are we going to stay stuck at lockscreen that could be designed by little kid? Lockscreen hasn't changed since WP7. I can't believe Microsoft didn't do anything about lockscreen in Windows 10 (Mobile). Great job MS, keep it like that, you'll get 5% of market in 2020 with that ideology.

**Comment by oldnewthing** [comment]
@Sweex Hey, I just run the samples repo. You're ranting at the wrong person.

**Comment by Sweex** [comment]
@oldnewthing I'm not ranting at you, I guess you don't have anything with OS APIs. I'm just saying how Microsoft needs 10 years to think about features that competition had years ago, and 10 years extra to build it (take a look at action center in WP8.1). I'm long-time Windows Phone and Windows developer but I'm tired of restrictions.

**Comment by oldnewthing** [comment]
@Sweex Ranting here doesn't really accomplish anything. This repo is for Windows samples, not for Windows OS design decisions. You might want to try the Feedback app for that. (Note also that you may want to take a more friendly tone when you submit to the Feedback app. People tend not to respond well to being insulted. Just a tip.)

**Comment by Sweex** [comment]
I'm not talking about design here. I'm talking how developers are restricted and can't do anything. I submited feedback since Insider program was launched and did they listen? No, and they won't listen. But they will continue to develop lockscreen that is worst than lockscreen on an old Nokia phone.

**Comment by pingzing** [comment]
Thanks for the quick reply, Mr. Chen. Closing this issue, as it sounds like something is in the works.
