### ISSUE TITLE
CallerID implementation throws a "Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))"

### ISSUE THREAD

**Issue by DarryStonem** [Microsoft/Windows-universal-samples#248]
I'm using the example of CallerID and when I'm trying to run it on my device it throws that exception. I'm in the 10586 build in my device.

**Comment by oldnewthing** [comment]
Can you isolate the problem to a specific line of code? What class is not registered?

**Comment by alexsorokoletov** [comment]
I don't see this error being thrown in the caller id sample, though when I tried to create a similar solution I got exactly the error described

**Comment by oldnewthing** [comment]
Since you say that the sample itself runs fine, the problem is elsewhere. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
