### ISSUE TITLE
Background Audio player (The RPC server is unavailable)

### ISSUE THREAD

**Issue by fpsqdb** [Microsoft/Windows-universal-samples#253]
The BackgroundAudio sample will throw exception ( The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)) with following step:
Run on windows 10 mobile device (10.10586.36).
1.Run BackgroundAudio app.
2.Suspend it.
3.Open Groove music and play a song.
4.Resume BackgroundAudio  app. then it will throw exception.

**Comment by fpsqdb** [comment]
Sorry, Pull the new code, it work fine.

**Comment by aarononeal** [comment]
That is by design. Background applications may be terminated to reclaim memory when no longer active. Generally a background audio task may continue to run for up to 5 without playing audio but its foreground counterpart may terminate sooner. If the app is launched again it can reconnect with its background task and manually restore its state.
