### ISSUE TITLE
WASAPI Audio not working in BackGround Task

### ISSUE THREAD

**Issue by Jeethan-Menezes** [Microsoft/Windows-universal-samples#268]
We are developing a VoIP Application and have a need to process the incoming call in the background beyond 30 seconds but we notice that background task gets suspended after 30 seconds on Windows 10 Mobile when we run this from Visual Studio debugger and it doesn't play any Audio in Background when we launch the app and put it in background, but the same code is working fine on the desktop. We are using WASAPI to record & play the audio.

I have uploaded the modified Sample project in 

https://drive.google.com/file/d/0B21RgZ6oQIFWckVLWGZvOFAxVjg/view?usp=sharing

**Comment by aarononeal** [comment]
WASAPI is not supported from a background task in UWP.  It works in most cases on desktop only because we have different background policies there that allow your task to run longer than on mobile.

The supported approach to background audio is shown here:
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackgroundAudio

You need to use BackgroundMediaPlayer. As you are developing a VoIP app you most likely will need to combine that with MediaStreamSource if you have a custom protocol and media container.  If there is a specific reason you must use WASAPI it can work inside the background audio task above provided you periodically play audio with the media player.

**Comment by Jeethan-Menezes** [comment]
Hi Aaron,

Thank you for your quick reply.

We have  tried BackgroundMediaPlayer but this worked when the API is called from foreground and then moved to background, but this didn’t work when I called this from background task.

Regards,
Jeethan

**Comment by aarononeal** [comment]
I need more details.

Did you try running the sample I linked? Did that work?

Background audio is only supported using a background audio task as demonstrated by the sample. If you are trying to do background audio from within any other task type it will not work because we go out of our way to prevent it.

**Comment by aarononeal** [comment]
Other things to check-- that you added the correct audio task extension entry to your package.appxmanifest and that you are setting up your media source from the task and not the foreground. You may also need to bind to the SMTC.

Please refer to our documentation here:
https://msdn.microsoft.com/en-us/library/windows/apps/mt282140.aspx

**Comment by Jeethan-Menezes** [comment]
Hi  Aaron,

If we acquire the audio channel in the foreground and keep it active in the background,then if we receive a GSM incoming call and after user has end the GSM call, would the background tasks still be able to play the audio.
if not, how can we play the audio again without moving the app into foreground.

**Comment by aarononeal** [comment]
All setup of the background audio source must be performed from inside the background task as the sample shows. You have to pass messages from the foreground to the background to setup the playback source. The documentation I linked explains this architecture. We do not support setting up audio sources in the foreground and then continuing to play in the background today. You must host the audio source from the background to begin with.

The only alternative is to use a "background capable media" audio category from a MediaElement or video tag.

https://msdn.microsoft.com/en-us/library/windows/apps/hh452730.aspx

This approach requires more resources and may only work well on desktop devices. We do not currently intend to support this approach in the future.

**Comment by aarononeal** [comment]
There is a walkthrough of the background audio sample here:
https://blogs.windows.com/buildingapps/2016/01/13/the-basics-of-background-audio/
