### ISSUE TITLE
 How to set the UriSource of GifView  to a local file?

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#303]
How to set the UriSource property of GifView to an uri to image file at Picture Library.

**Comment by oldnewthing** [comment]
You don't need to. Modify the `GifView` class so it uses a `RandomAccessStreamReference` instead of a `Uri`. This is really not a question about the sample; it's a question about how to modify the sample to do something new. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel

**Comment by HppZ** [comment]
Thanks for the reply!
I already modified the GifView class to support using StorageFile as param directly.
