### ISSUE TITLE
BackgroundPlayer crashes when clicking on label or albumart

### ISSUE THREAD

**Issue by hig-ag** [Microsoft/Windows-universal-samples#304]
When you play a track in the BackgroundAudio Sample and click either on the title label or the album art on the SystemMediaTransportControls (shows up in the left top corner when changing volume) the BackgroundAudio process crashes without an exception.

My system: Windows 10 Build 10586

**Comment by LtCmdrKeene** [comment]
I see this too:

**Comment by aarononeal** [comment]
@hig-ag I have reproduced this and passed along to the team for an update.

@LtCmdrKeene I think you've hit a different issue since that exception you should only receive in the foreground app not the background task that is crashing. If you share the stack trace or line of code that is failing I might be able to make a recommendation.

**Comment by aarononeal** [comment]
@hig-ag we have an internal platform bug tracking this issue. Sorry for the inconvenience. Keep an eye out for a fix in future Windows builds.
