### ISSUE TITLE
Memory leak with Printing C# Sample?

### ISSUE THREAD

**Issue by laviassister** [Microsoft/Windows-universal-samples#333]
For a Printing C# Sample for Uiversal Windows Application

1) build
2) select the scenario4 , push PrintSelection ,  canceled after the print preview came out
3) select the scenario5 , push Print , canceled after the print preview came out
4) Repeat 10 times 2)-3) 
result, a large amount of memory is leaked.
Whether there is a problem in procedure of calling the sample
 , or the bug of Windows 10?

**Comment by jajamatu** [comment]
Hi,

I have the same issue with the provided printing scenario and I would be very happy if somebody could tell me how to avoid the memory overflow.
I have just started learning programming with uwp this year - but this Problem tracks me already for more than 5 hard and frustrating weeks of trying to get a head on it.

I have programmed a little app where the user can easily create a purchase list with different products.
Now I want to implement the option that the user can also print this list. This is necessary beacuseof different reasons.

Therefore I have studied the Scenario 1 of the provided printing sample.
But when I run this example on my Lumia 650 the app gets a Memory Overflow by operating like this:
  1) Select Scenario 1 and press the button for printing
  2) cancel the upcoming printpreview
  3) select Scenario 2 without doing anything else (just to unregister the Printer outof Scenario 1)
  4) select once again Scenario 1 and repeat the procedure for 9-12 times

The same behavior can be monitored with the Lumia 950 - even if it takes more times of repeats to get the exception thrown becauseof the greater memory.

By catching the thrown exception I get the message:
  _"Insufficient memory to continue the execution of the program." 
    HResult: -2147024882_

This exception is thrown in the procedure getPrintPreviewPage(...) before this code-line is executing:
  _"printDoc.SetPreviewPage(e.PageNumber, printPreviewPages(e.PageNumber - 1))"_

I'm really desperate because I have already tried so much to avoid this Memory leak with different attempts. 
But nothing works. 
And I don't find the object that is responsible for the Overflow.

Maybe someone could help me to solve this Problem?

Kind regards from Germany,
Janine

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team has confirmed a memory leak. They are working to fix it. Thanks for reporting.

**Comment by laviassister** [comment]
Thank you for fixing!

**Comment by oldnewthing** [comment]
Yes, the feature team is working on the fix. The memory leak is not due to a bug in the sample, so the samples issue remains closed. You are welcome to open a Feedback Hub item to report the platform issue.

**Comment by ryancairnsy** [comment]
We have recently discovered this bug is causing major problems on our kiosk mode LOB app because of the increase in memory every time the users print (the app does not get restarted). Is there anywhere else I can log this as an issue to try and get updates on progress etc?

**Comment by oldnewthing** [comment]
You can open a Feedback Hub item. I think "Developer Platform" is the category.

**Comment by ryancairnsy** [comment]
Thanks - I have done that now. https://aka.ms/AA22cmx

**Comment by jeanmarc3** [comment]
I'm having the same issue but can't find where this fix has been posted.  Any help?

**Comment by ryancairnsy** [comment]
The issue is not fixed as of build 1809. We are now disabling the print
preview on our LOB which results in a massive memory reduction.

**Comment by jeanmarc3** [comment]
Thanks Ryan for the answer.  It is a bit scary that Microsoft seems to drop UWP support completely (starting with Office apps...).  Did you end up writing your own print preview screen, or just do like Scenario 6 or the sample app?

**Comment by jeanmarc3** [comment]
This print issue exists since 2016.  Also:
[https://winbuzzer.com/2018/09/28/microsoft-explains-why-it-is-ending-office-uwp-app-feature-support-xcxwbn/?fbclid=IwAR2zQKZwhXE2oXDyMgf8EExKUgZKRlDkPbbbO5ZUdgl4s1zFqGUU6VuShCU](url)

**Comment by zanamziry** [comment]
its almost 2021 and they still didn't resolve this issue, print 10 pages and 1GB is wasted...

**Comment by michaelrinderle** [comment]
i will say the same. still not fixed. what are UWP developer to do with this? any pointers on certain parts of the code that we can make sure their objects are getting destroyed by explicit garbage collection? ive tried everything and this is a huge leak. customers are expecting to have a print preview dialog.

**Comment by baskren** [comment]
Why is this closed - it's well into 2021 and this is definitely not fixed.

**Comment by oldnewthing** [comment]
Because it's not a bug in the sample. It's a bug in the OS.

**Comment by michaelrinderle** [comment]
i'll re-phrase for @baskren :
why hasn't this been passed on to the OS devs in over 4 years?

@baskren I had to drop print preview report because I wouldn't let the app go into the wild with this leak. I opted to just download the PDF and launch from the default pdf program.

**Comment by baskren** [comment]
@oldnewthing:  Thanks for confirming.  My angst was (slightly) misdirected.

@michaelrinderle : Yes, I've had to disable printing on 32 bit builds because of this.

**Comment by baskren** [comment]
@oldnewthing : Should have added one more thing ... per your Aug 15, 2018 comment

> You can open a Feedback Hub item. I think "Developer Platform" is the category.

I can't say how much I wish this was helpful.   It's almost as if Feedback Hub is where all well intentioned issue go to die.  Is there any chance there is a GitHub repo that we could report this issue?

**Comment by oldnewthing** [comment]
> Why hasn't this been passed on to the OS devs in over 4 years?

I forwarded it to them when the issue was opened in 2016 but never heard back. I went and kicked the thread again.

**Comment by baskren** [comment]
@oldnewthing : I would be happy to provide a demo project and submit a bug report / issue ... if I knew it was going to be seen and be helpful to the devs.

**Comment by pratikpc** [comment]
@baskren this was apparently fixed in Windows 11 Insider Preview Build 22000.65

I guess @oldnewthing forwarding it again led to it getting fixed

https://blogs.windows.com/windows-insider/2021/07/08/announcing-windows-11-insider-preview-build-22000-65/

**Comment by baskren** [comment]
@pratikpc -  Thank you for closing the thread.
