### ISSUE TITLE
StreamSocket sample is invalid

### ISSUE THREAD

**Issue by jwettstrom** [Microsoft/Windows-universal-samples#354]
The C# StreamSocket sample is invalid. It is calling itself. It should be a client and a server in separate executables/projects!

**Comment by SidharthNabar** [comment]
@jwettstrom - The StreamSocket sample can be run on two separate machines, one acting as the server side and the other one acting as the client side. The only change needed is to enable the “HostNameForConnect” textbox in Scenario2_Connect.xaml.

The actual code does not change at all. By default, the sample uses loopback communication in order to reduce the likelihood of networking issues since those are unrelated to the StreamSocket APIs being showcased.

**Comment by jwettstrom** [comment]
Yeah, but not everyone have two machines to test on, so not good for a lot of people. Plus if I split the apps up, I can't get it to work at all on same machine using localhost as hostname. Maybe something worth looking into. There would also be good to have a WebSocket client server sample app (both apps be UWP).

**Comment by DelfCo** [comment]
Windows Store apps can't establish socket connections (Sockets API or Winsock) between two apps running on the same machine. This has been part of the network isolation design for UWP (Windows Store) apps since Windows 8, and is designed to ensure that UWP apps are well-behaved and stay within their own sandbox. (See a typical past discussion [here](https://social.msdn.microsoft.com/Forums/en-US/6835a50c-2830-41db-a95d-6b9555c8eea2/network-isolation-can-i-use-loopback-within-my-app-and-get-it-in-the-store?forum=winappswithcsharp). ) This is why the sample demonstrates communication between a server component and a client component packaged as a single app, rather than giving you separate server and client apps -- it's the only way to demonstrate both sides of a socket communication using UWP apps on a single machine. 

I was going to quote our docs about this, but didn't find it in the most obvious places. I'll be adding some clarification about this to the docs in the next day or two. Thanks for highlighting the need for a doc update.

**Comment by jwettstrom** [comment]
Sorry that just doesn't make sense in some use case scenarios. Also, you should be able to be sandboxes and still call across apps through sockets if the network classes (at whatever level) was implemented correctly. So to do a workflow on a machine now you have to build a local run "service" app that acted as go between. That is just silly. Sorry but whoever came up with this idea hasn't looked into some business scenarios.

**Comment by oldnewthing** [comment]
This discussion doesn't appear to be related to the sample any more.
