### ISSUE TITLE
AudioCapture Scenario 2 Device Capture not working

### ISSUE THREAD

**Issue by hexate** [Microsoft/Windows-universal-samples#360]
I'm trying to get Scenario 2 Device Capture in the AudioCapture solution to work, but it is not happy. I am prompted to select an output device from a list (I choose my speakers) and then I click the "Create Graph" button. The UI immediately blinks with buttons enabling and disabling, and it does not continue. 

After hooking up an event handler to UnrecoverableErrorOccurred, it looks like AudioGraphUnrecoverableErrorOccurredEventArgs.Error is set to AudioDeviceLost. Any ideas what situation would cause that error to occur? Keep in mind, I am not able to attempt recording yet, I am trying to create and configure the graph only.

**Comment by balasiv** [comment]
Hi Hexate,
I just tried the sample and it works fine for me. I suspect it is an issue with your audio hardware/setup on your device and not an issue of the sample code.

This issue is not related to a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account.
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
