### ISSUE TITLE
VOIP and App Service

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/Windows-universal-samples#390]
Hi,
after reading the voip app example, I don't understand one thing. Do I need app service to create voip app? Or is it recommended? As I know, app services are used to communicate between different apps.

Thanks for your answer

**Comment by lstachowicz** [comment]
Hi,

You need to have AppService for communication with background (In background you are hiding your VoIP process in order to not be suspended):
https://github.com/Microsoft/Windows-universal-samples/issues/405

There is new way of creating background task but it will not work for VoIP because of VoipHost process:
https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/#25Jk9qsIZwgoSv0m.97
