### ISSUE TITLE
VoipHost.exe in Voip example

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/Windows-universal-samples#405]
Could someone tell me, for what is VoipHost project in voip example?

**Comment by yehe01** [comment]
Same question here. I guess it's some magic.

**Comment by JurajPupak** [comment]
I think I've solved this problem after long time searching. VoipHost is out-of-process server. It is .exe. In this process the backgroundtask (CallRTCTask) and AppService are hosted. As you can see in PackageManifest file, CallRTCTask has attribute ServerName="VoipHost". Same for AppService. VoipHost is the server that the foreground app and the background components use to communicate between processes.
Here is picture from Chatterbox, it is the same principle.

**Comment by chenjianwp** [comment]
there will no specialist to confirm your statement..... as for wp8 chatbox sample ,I have the same question,no one answer me^-^

**Comment by lstachowicz** [comment]
VoipHost is out-of-process server for your background application as you mention.

You can have all in one but them you will mess-up your GUI for your VoIP. In order to fix it you need new executable that will be working in background and it will have possibility to start an "Application". VoipHost will be started by AppService and can be suspended by system if there is no alive connection AppService or your VoIP background task is closed.

It is worth to mention that you can't start/deploy VoipHost as stand alone application. It have to be a part of other application.

**Comment by JurajPupak** [comment]
I think, I cannot have all in one, because, if the app is suspended, the call is suspended too.
So if I understand it correctly, for VOIP app is good to have multiprocess model. VoipHost.exe is hosting AppService, CallRTCTask (as in sample). Where should be socket background task (SocketActivityTrigger)  hosted? On VoipHost.exe or on GUI?

**Comment by lstachowicz** [comment]
Hi,
The best will be if you will treat background a logical part and foreground as visual part. Having logic in both processes can become complicated.

**Comment by JurajPupak** [comment]
and GUI should communicate with background (logic) through app service? Am I right?

**Comment by lstachowicz** [comment]
Yes, tricky part is to write correct sync. Because if you fail you will lose connection and will be out of sync.
