### ISSUE TITLE
Samples / Nfc / Nfc / CardReader.xaml.cs :: if (!deviceInfo.IsEnabled)

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/Windows-universal-samples#421]
On Windows 10 Anniversary Update builds `deviceInfo.IsEnabled` is always `true` on Lumia 650.
On official (previous) builds it worked as expected.

Is it bug of new version of Windows? Do I need write bug reports to someone? Or you can do it?
Or something changed in it and now problem in your sample code?

thank you.

**Comment by oldnewthing** [comment]
Feature team says that this bug is not relevant since [Windows 10 Mobile Anniversary Update has exited support](https://support.microsoft.com/en-us/help/4468548/windows-10-mobile-released-in-august-2016-end-of-servicing). The issue exists only in the Phone code base and does not affect Windows going forward.
