### ISSUE TITLE
Cant read the text that NotePad save

### ISSUE THREAD

**Issue by lindexi** [Microsoft/Windows-universal-samples#425]
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/FileAccess/cs/Scenario3_WriteAndReadTextInAFile.xaml.cs

When I read the file that I use Notepad save and encoding is ASCII and the text have Chinese that it throw  ArgumentOutOfRangeException " No mapping for the Unicode character exists in the target multi-byte code page".

And when I use the 

```

                IBuffer buffer = await FileIO.ReadBufferAsync(file);
                DataReader reader = DataReader.FromBuffer(buffer);
                byte[] fileContent = new byte[reader.UnconsumedBufferLength];
                reader.ReadBytes(fileContent);
                string text = Encoding.ASCII.GetString(fileContent, 0, fileContent.Length);
```

text is "?" when Chinese char.

http://stackoverflow.com/questions/35296213/read-unicode-string-from-text-file-in-uwp-app/38299563#38299563

**Comment by oldnewthing** [comment]
As noted in the StackOverflow article you linked to, the issue is with the encoding. `DataReader` defaults to UTF-8 encoding, but you didn't save the file as UTF-8. This doesn't appear to be a question about the sample, which always uses UTF-8 encoding.

You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by lindexi** [comment]
Chinese is GBK encoding and I can use 

    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
    Encoding encodingGbk =Encoding.GetEncoding("GBK");

http://www.win10.me/?p=938

**Comment by Andy001847** [comment]
Thank you for your help！

发件人: lindexi [mailto:notifications@github.com]
发送时间: 2016年7月26日 18:35
收件人: Microsoft/Windows-universal-samples <Windows-universal-samples@noreply.github.com>
主题: Re: [Microsoft/Windows-universal-samples] Cant read the text that NotePad save (#425)


Chinese is GBK encoding and I can use

Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

Encoding encodingGbk =Encoding.GetEncoding("GBK");

http://www.win10.me/?p=938
