### ISSUE TITLE
PosPrinter, ARM, .Net Native tool chain

### ISSUE THREAD

**Issue by Shluzzz** [Microsoft/Windows-universal-samples#433]
Sample (PosPrinter) does not work for ARM processor with the option ".Net Native tool chain". Method "DeviceInformation.FindAllAsync" return NULL. Without option ".Net Native tool chain" sample work ok, for X86 and x64 work ok too (with and without Native tool chain option). Printer Epson TM-T20.

**Comment by tommykdev** [comment]
I downloaded the sample, compiled the C# app with the .net native option, deployed, and successfully ran it with an Epson printer. 

Not sure what version of Visual Studio 2015, Windows SDK, and OS images you may have used, but the following versions worked: Visual Studio 2015 Verison 14.0.25431.01 Update 3;  Windows version 1511 10.0.10586 or later on Arm phone or PC/Tablet.

I think the FindAllAsync() method returns null if no printer can be found, which in your case may be a transient pairing or network/bluetooth issue, rather than how compiled.  Perhaps unpair the printer to make sure.  

Assuming your Arm device is a Windows 10 (build 10586 or later) you might try to download a Windows Store Win10 App that connects to PointOfService devices, just as a diagnostic, and test with your Epson PosPrinter setup. UWP PointOfService Apps utilize the same API surface.  And the UWP Store apps are compiled with .net native.
