### ISSUE TITLE
Multiple Views Sample for Javascript?

### ISSUE THREAD

**Issue by bschelling** [microsoft/Windows-universal-samples#441]
The multiple views in the samples only shows a CS version.
The old (8.1) sample works only with winjs 2.0 which can't be installed with nu-get.
Additional Info is here
https://brentdacodemonkey.wordpress.com/2016/03/23/multiple-windows-with-windows-10-and-javascript/

Any plans to get a Multiple Views Sample in JavaScript?

**Comment by michael-hawker** [comment]
I found it pretty easy to just create a new blank Win10 WinJS project in VS, dump in the old sample content, and then update the path for the WinJS lib.

It'd be nice though if we could just remove the WinJS dependency from all these samples, as in most cases it's not really used for anything more than what can be done in JavaScript already.  Plus, it's confusing when the docs.microsoft.com don't use it in the majority of their snippets, but then it's used here.  

Plus, it's harder for devs with existing sites making PWAs that want to integrate new features to have to learn a new dependency vs. just being able to use raw JavaScript examples.  Especially when that dependency says it's no longer adding new features.

**Comment by bschelling** [comment]
so to be honest I'm surprised anybody is still using the winjs stuff.
its pretty much dead and I don't feel sorry about it
https://github.com/winjs/winjs/graphs/contributors

**Comment by oldnewthing** [comment]
I put an item on the feature team's backlog.

**Comment by hiepxanh** [comment]
thanks god, @oldnewthing  you are saving my life, I cannot my angular typescript carrier without that API, but it seem we do not have example, you can help me with that. 
And, an small question, do you know when or there is any intent to make javascript (or typescript) for the microsoft document ? I only see C#

**Comment by oldnewthing** [comment]
I don't know what you mean "any intent to make javascript for the Microsoft document". What document are you referring to? I think the old 8.1 JavaScript sample still works, except that you have to change `new MSAppView` to `window.open`.

**Comment by hiepxanh** [comment]
There is only thing on here: [UWP js example](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-js-apps) for UWP.
1) 
![image](https://user-images.githubusercontent.com/16970990/33108668-f9d0a990-cf6f-11e7-95f4-2c6f3c4e3541.png) other feature like UI design, develope app not have example for javascript but API does. Why dont you make it for javascript, I don't know any different resource. If you have intent, when ? 
![image](https://user-images.githubusercontent.com/16970990/33108704-2a8e76d4-cf70-11e7-8998-87c9414a734a.png). why dont you make this ? 
2) we should make a migration guide for developer, so It doesn't take few hour for just because I don't know have to change `new MSAppView` to `window.open.`
3) fail tutorial. for example.
[multiple-view for UWP 10](https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views)
- I cannot follow because: you have excellent guide but you don't show the top, what should we import ?
![image](https://user-images.githubusercontent.com/16970990/33108905-3a63c3f6-cf71-11e7-9f96-1e4c68bd0c3b.png)
ok, intelligence help to recommend, but what is SecondaryPage? where did I get ? how can I run without example to check ?

That all, I'm not offence you or blame or something, I hope you can share my opinion, because I event cannot login to make any comment or question. 
![image](https://user-images.githubusercontent.com/16970990/33109035-db866252-cf71-11e7-847e-e5a97d490713.png)
have a good day sir. I alway admire you effort. Did you do this repository and event microsoft guide all ?

**Comment by oldnewthing** [comment]
I'm having trouble following what you're saying, but I think you're saying is that the documentation on docs.microsoft.com is too focused on C# and XAML and not enough on the other languages. I'll pass this feedback to the documentation team.

**Comment by hiepxanh** [comment]
thank you sir, that's very kind of you. I'm felling your helping as warm as my father. I hope I can help you something in that repository, I can't let you just doing that super big repository alone

**Comment by Jaifroid** [comment]
Can we please have some documentation for creating multiple views in JavaScript UWP apps? I understand we're supposed to use `window.open` rather than the WinRT API that wasn't implemented in Windows 10 JS, but there's literally zero help from MS on this. JS is supposed to be a "first-class" language for UWP apps, but it feels like third-class.

**Comment by oldnewthing** [comment]
Sadly, Visual Studio 2019 dropped support for JavaScript UWP apps, so there's nothing that can be done in this repo. Yes, you use `window.open` to create a new window.

**Comment by Jaifroid** [comment]
@oldnewthing May I point out that PWAs (which are written in JavaScript of course) are still fully supported, and that PWAs that are packaged as Store apps have full access to the UWP APIs? Therefore, I think there is still a place for JavaScript samples in this repository. It would be a very regressive move to remove them, as this repo is one of the few sources of information available to developers who are writing JS store apps or PWA apps that need to interact with the OS, albeit that developers currently have to use VS Code or Visual Studio 2017.

**Comment by oldnewthing** [comment]
My hands are tied. Visual Studio 2019 doesn't support JS UWP apps, and this is the UWP repo. That said, you can take the old Windows 8.1 Multiple View JS sample, and with very small tweaks it still runs on Windows 10.
