### ISSUE TITLE
FilePickerContracts: OnCachedFileUpdaterActivated doesn't get called on WP10

### ISSUE THREAD

**Issue by limered** [Microsoft/Windows-universal-samples#474]
Repro:
1. Deploy File Picker sample
1. Deploy the FilePickerContracts
2. Run "File picker C# sample"
3. Click Scenario 4, "Save a file"
4. Select the "File Picker Contracts" app
5. Select option 3, "Save to cached file" (if debugging, you may have to detach before this step. File pickers don't seem to respond to click events while debugging)
6. Click "Save"

If you are debugging the FilePIckerContracts app, set a breakpoint in the method "OnCachedFileUpdaterActivated". On WinPhone the breakpoint will not be hit. On Win10 the breakpoint will be hit.
Plus, the file could not be saved message in "File picker sample".

I also tried saving files from Excel Mobile. I also implemented Office Intergration in an app with the same (failed) result after the opened file has been saved by office.

**Comment by FUR10N** [comment]
I ran into this issue as well but never got anywhere with it.
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a49324b1-da98-4b7c-bb7c-78edd495ca8a/uwpwindows-phone-10-file-save-picker-not-working?forum=wpdevelop
http://stackoverflow.com/questions/35162094/windows-phone-10-file-save-picker-not-working

**Comment by duglah** [comment]
I'm having the same problem.
Even the sample isn't working...

But seems like Dropbox and Onedrive can handle this...

**Comment by SunboX** [comment]
Same for me. :( Maybe Dropbox was build using a older framework version? But how does Onedrive handle this?

**Comment by oldnewthing** [comment]
The feature team informs me that they addressed this issue in the Creators Update. Let us know if this issue is still occurring.

**Comment by Lazzarus** [comment]
I'm still seeing the issue on the Creators update build 15063. 
I'm currently unable to try the Fall Creators update (16299) nuget issue with 16299. 
Which version should the fix be in?

**Comment by oldnewthing** [comment]
@Lazzarus I've asked the feature team to double-check .

**Comment by Lazzarus** [comment]
Thanks @oldnewthing . I've got the sample running under 16299 now. The cached file save picker works fine but the cached file open picker sample doesn't seem to.

I've done some testing and looking at FileOpenPicker_PickCachedFile.xaml.cs there is a method AddFileButton_Click which creates a txt file with text content and then sets up the CachedFileUpdater.SetUpdateInformation with ReadActivationMode.BeforeAccess but the OnCachedFileUpdaterActivated never fires.

It looks incorrect to me,  I would have expected the content of the txt file to be created by the CachedFileUpdater firing on the BeforeAccess read activation mode and I suspect creating the content on the creation of the file is hiding the issue off the CachedFileUpdater not activating.

**Comment by oldnewthing** [comment]
The feature team says that they tested on the public build of Windows Phone (152xx) and OnCachedFileUpdaterActivated is being called.

**Comment by Lazzarus** [comment]
Still not seeing it called on before access. Sticking a break point on OnCachedFileUpdaterActivated never gets hit. I on Desktop creators update (16299)

As mentioned the example is a bit odd. Surely the content on the txt file should be created when the before access event fires and not when creating the file. 

After Access will cause the break point to be hit.

**Comment by Lazzarus** [comment]
I've run across a couple of other issues.

The first is easy to replicate. Start the FilePickerContract app and make sure the GUI is showing. Now start the paint 3D app, create a picture and save it. Pick the FileContractPicker app -> Option 3 Saved to Cached file. Now Save.  After Saving Attempt the close the FilePickerContract app and you will be presented with a dialog stating 'Your using File Picker Contracts #C in another app to save a file'

I am seeing this in my own app and my guess is deferral.Complete(); isn't releasing the deferral.

**Comment by Lazzarus** [comment]
The other issue is a bit harder to replicate .

Basically the page size is reported as the whole Screen size and not the dialog size some times causing layout issues. This appears to be a race condition. If you display the page quickly everything works but if you do anything during the page creation the size is reported wrong in both the Xaml and Page size events report the size as the screen size as the complete display size and not the dialog.

The example works because it doesn't do much when displaying the page and creates in up front with             `var FileOpenPickerPage = new SDKTemplate.FileOpenPickerPage();            FileOpenPickerPage.Activate(args);`
and then 
```
         public void Activate(FileOpenPickerActivatedEventArgs args)
        {
            // cache FileOpenPickerUI
            fileOpenPickerUI = args.FileOpenPickerUI;
            Window.Current.Content = this;
            this.OnNavigatedTo(null);
            Window.Current.Activate();
        }
```

The problem occurred for me when creating a frame and then `frame.Navigate(typeof(myPage));` with a setup for the page in the OnNavigatedTo. The slight increase in the time to display the pages causes the size to be reported incorrectly

I've been able to work around the issue by creating the page as per the example and then add altering the activation to 
```
        public void Activate(FileOpenPickerActivatedEventArgs args)
        {
            _fileOpenPickerActivatedEventArgs = args;
            Window.Current.Content = this;
            Window.Current.Activate();
            OnNavigatedTo(null);
            DeferedInit();
        }
```
and for the extra DeferedInit();

```
        public async void DeferedInit()
        {
                // DO NOT REMOVE. REQUIRED TO MAKE DEFER FIX WORK.
                await Task.Delay(100);
               DO SOME LONG RUNNING TASK LIKE CALL WEB API
        }
```

Apart from the dirty Task.Delay there's also a disadvantage of the the OnNavigatedTo and OnNavigatedFrom events not firing when initializing the page in this manner which makes cleaning up events registered to problematic.
