### ISSUE TITLE
PrintTask DisplayedOptions do not show

### ISSUE THREAD

**Issue by ThanawutZiios** [Microsoft/Windows-universal-samples#486]
Hi ,

I try to run Sample\Printing\js and try to add option into print dialog by

 printTask.options.displayedOptions.push(
                Windows.Graphics.Printing.StandardPrintTaskOptions.copies,
                Windows.Graphics.Printing.StandardPrintTaskOptions.mediaSize,
                Windows.Graphics.Printing.StandardPrintTaskOptions.orientation,
                Windows.Graphics.Printing.StandardPrintTaskOptions.duplex,
                Windows.Graphics.Printing.StandardPrintTaskOptions.binding,
                Windows.Graphics.Printing.StandardPrintTaskOptions.collation,
                Windows.Graphics.Printing.StandardPrintTaskOptions.colorMode,
                Windows.Graphics.Printing.StandardPrintTaskOptions.holePunch,
                Windows.Graphics.Printing.StandardPrintTaskOptions.inputBin,
                Windows.Graphics.Printing.StandardPrintTaskOptions.mediaType,
                Windows.Graphics.Printing.StandardPrintTaskOptions.nup,
                Windows.Graphics.Printing.StandardPrintTaskOptions.printQuality);

but it still show me only 3 value on printer,papersize and orientation.

my window is version 10.0.14393

Thank you,

**Comment by oldnewthing** [comment]
I cannot reproduce this problem. When I apply the code change you describe, the print dialog shows a lot of options. So many they don't even fit in the dialog box without a scroll bar.

![image](https://user-images.githubusercontent.com/12550607/32294903-df9d1a02-bf04-11e7-9bed-0f9512e0d63d.png)

Hole Punch doesn't show up because my printer doesn't have a hole puncher. Maybe your printer doesn't support the missing options?
