### ISSUE TITLE
How to detect incoming call hang up

### ISSUE THREAD

**Issue by soroshsabz** [Microsoft/Windows-universal-samples#493]
ITNOA

Hi, I see [Communication blocking and filtering sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CommunicationBlockAndFilter) but I could not find anyway to detect when incoming call hang up, I see [PhoneTriggerType enumeration](https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.calls.background.phonetriggertype.aspx) but some description is very unclear.

I think CallHistoryChanged trigger maybe helpful but after I register background task for this type, my background task never call when I call to my phone or call from my phone or any missed call.

I ask the question in [stack overflow](http://stackoverflow.com/q/39789076/1539100) but I couldn't found any solution.

Can any body help me?

thanks a lot

**Comment by oldnewthing** [comment]
Communication blocking and filtering is for detecting the start of a call, not the end. If you are asking a question about UWP in general rather than about a specific sample, you can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
