### ISSUE TITLE
How to adapt the sample MasterDetailSelection for allowing editing?

### ISSUE THREAD

**Issue by Goldstrike** [Microsoft/Windows-universal-samples#524]
Hello,
I based on the sample ListView - MasterDetailSelection to allowing the edition of the selected item, but it doesn't word.
(https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlListView/cs/Samples/MasterDetailSelection)
Is it feasible? Or is in another way to do this?

**Comment by oldnewthing** [comment]
This is a question about writing a new app, using the sample as a guide, rather than a question about a sample that not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.Leave a comment
