### ISSUE TITLE
DatagramSocket Scenario5 is shortcircuited

### ISSUE THREAD

**Issue by m1chal1s** [Microsoft/Windows-universal-samples#529]
The only reason why UDP broadcasting appears to work is because the same instance of the `DatagramSocket` is used for broadcasting and for receiving the message. 

If you configure the transmitter to use its own instance, and configure it the same way, bad stuff happens.

Say that you edit `SendMessage_Click` as follows:

```c#
        private async void SendMessage_Click(object sender, RoutedEventArgs e)
        {
            SendOutput.Text = "";

            try
            {
                IOutputStream outputStream;
                HostName remoteHostname = new HostName(RemoteAddress.Text);
                var listenerSocket2 = new DatagramSocket();
                await listenerSocket2.BindServiceNameAsync(ServiceName.Text);

                // GetOutputStreamAsync can be called multiple times on a single DatagramSocket instance to obtain
                // IOutputStreams pointing to various different remote endpoints. The remote hostname given to
                // GetOutputStreamAsync can be a unicast, multicast or broadcast address.
                outputStream = await listenerSocket2.GetOutputStreamAsync(remoteHostname, ServiceName.Text);

                // Send out some multicast or broadcast data. Datagrams generated by the IOutputStream will use
                // <source host, source port> information obtained from the parent socket (i.e., 'listenSocket' in
                // this case).
                const string stringToSend = "Hello";
                DataWriter writer = new DataWriter(outputStream);
                writer.WriteString(stringToSend);
                await writer.StoreAsync();

                SendOutput.Text = "\"" + stringToSend + "\" sent successfully.";
            }
            catch (Exception exception)
            {
                // If this is an unknown status it means that the error is fatal and retry will likely fail.
                if (SocketError.GetStatus(exception.HResult) == SocketErrorStatus.Unknown)
                {
                    throw;
                }

                rootPage.NotifyUser("Send failed with error: " + exception.Message, NotifyType.ErrorMessage);
            }
        }
```

This will, rightly, cause an exception to be thrown:
![image](https://cloud.githubusercontent.com/assets/3284819/20398668/98a39bea-acee-11e6-912c-faedd6235625.png)

Please have a look, and let me know if I can help. I really haven't found a good example of UDP broadcasting under UWP, and I'd like to see this one in working order.

BTW, the same thing happens in c#, c++, and js.

**Comment by m1chal1s** [comment]
BTW, the same thing happens in c#, c++, and js.

**Comment by DavidGoll** [comment]
The issue is that the code is attempting to bind to the same local port with two different DatagramSockets. This is not supported for unicast UWP sockets, as it would enable other local processes to hijack and/or eavesdrop on a UWP app’s traffic, effectively breaking the UWP isolation model. The broadcast scenario uses unicast binds, so the same restriction applies.

Multicast-only scenarios (i.e., DatagramSockets explicitly configured with MulticastOnly=’true’) do support local port sharing because the UWP app is declaring that the socket will never be used to receive unicast packets, so it is fine for other local processes to use the same port for receiving their multicast traffic as well.

Port sharing aside, the main thing to note is that the sender socket does not need to do an explicit bind to a specific port. Calling GetOutputStreamAsync is sufficient for the sender socket to transmit broadcast packets to the other (listening) socket. The GetOutputStreamAsync call will do an implicit bind to a random/ephemeral local port if Bind*Async hasn’t been called on it. In broadcast protocols, the receivers/listeners bind to a specific port, but the senders bind to a random port. Once the listener receives a broadcast packet, it can reply to the sender by retrieving the “source port” from the incoming UDP packet.

Last but not least, I’d like to point out that the DatagramSocket sample can be deployed in two separate devices inside the same LAN and verify that the full end-to-end broadcast scenario works with the current version of the sample.

**Comment by m1chal1s** [comment]
No, that is not the issue. The code in above is bad - I wrote it to demonstrate that even if we dupicate the DatagramSocket, we still would not get the sample to work.

The issue, as I wrote, remains:
> The only reason why UDP broadcasting appears to work is because the same instance of the `DatagramSocket` is used for broadcasting and for receiving the message.

Yes, running the sample on two devices will get it to work. Here's the problem, though: It will appear to work even if the two devices are connected to different networks!

I do not see how that could be the intended behavior.

By the way, I am writing about the Broadcasting part of scenario 5. I have no opinion on the rest of the sample.

**Comment by dabbers** [comment]
After investigating the issue, we've found that there was an issue where DatagramSockets would not broadcast to all network adapters.

You can work around this by either removing the additional adapters (particularly the virtual switch included with Hyper-V causes issues). Keep in mind, you can receive broadcasts while having multiple adapters. 

We'll be fixing this in a future version of Windows.
