### ISSUE TITLE
Use bluetooth in Remote System sample

### ISSUE THREAD

**Issue by piotrbalut** [Microsoft/Windows-universal-samples#530]
How I can specify type of proximity connection? For example bluetooth? The sample uses only wifi and there are a problems with firewall on my pc. Is there any way to connect via bluetooth or wifi (but when firewall is turned on)?

**Comment by oldnewthing** [comment]
This appears to be a question about the RemoteSystems feature rather than a question about the sample. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
