### ISSUE TITLE
EventHandlerForDevice.cs (in serial examples) mixes UI and data layer code

### ISSUE THREAD

**Issue by wind-rider** [Microsoft/Windows-universal-samples#550]
The [```EventHandlerForDevice.cs```](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SerialArduino/cs/EventHandlerForDevice.cs) file has a lot of mixed references.

The code would be clearer if it the references to UI code (App, MainPage, etc) would be separated from the SerialPort code.

Say that people want to make a library that provides functions to perform certain Serial port commands - how would this class look like then?

**Comment by oldnewthing** [comment]
The purpose of the UWP samples is not to be a library. It is to demonstrate proper use of an API as simply as possible. In general, this means having event handlers updating UI directly instead of hopping through two levels of indirection (model and view model) which are harder to follow if you are trying to understand how an API works.
