### ISSUE TITLE
Adding code for playing H.265 (a.k.a. HEVC) video stream with MediaElement via MediaStreamSource

### ISSUE THREAD

**Issue by zipswich** [Microsoft/Windows-universal-samples#569]
MediaElement supports HEVC (H.265), however VideoEncodingProperties does not have a method for creating an instance for H.265 like the one for H.264.  This means an instance of VideoEncodingProperties for H.265 needs to be created and configured manually. I don't know if the use of MediaStreamSource is different from its use for H.264.  A working sample will be greatly appreciated.

**Comment by damingerdai** [comment]
ok

**Comment by aarononeal** [comment]
Thank you for the feedback.

CreateHEVC() is available in current RS2 flights.

Prior to that, you can construct the type manually and set the subtype for HEVC and the usual framerate and resolution parameters. You also need to set the ProfileId to one of these enum values, likely the value 1.

enum eAVEncH265VProfile  
{  
   eAVEncH265VProfile_unknown           = 0,  
   eAVEncH265VProfile_Main_420_8        = 1,  
   eAVEncH265VProfile_Main_420_10       = 2,  
   eAVEncH265VProfile_Main_420_12       = 3,  
   eAVEncH265VProfile_Main_422_10       = 4,  
   eAVEncH265VProfile_Main_422_12       = 5,  
   eAVEncH265VProfile_Main_444_8        = 6,  
   eAVEncH265VProfile_Main_444_10       = 7,  
   eAVEncH265VProfile_Main_444_12       = 8,  
   eAVEncH265VProfile_Monochrome_12     = 9,  
   eAVEncH265VProfile_Monochrome_16     = 10,  
   eAVEncH265VProfile_MainIntra_420_8   = 11,  
   eAVEncH265VProfile_MainIntra_420_10  = 12,  
   eAVEncH265VProfile_MainIntra_420_12  = 13,  
   eAVEncH265VProfile_MainIntra_422_10  = 14,  
   eAVEncH265VProfile_MainIntra_422_12  = 15,  
   eAVEncH265VProfile_MainIntra_444_8   = 16,  
   eAVEncH265VProfile_MainIntra_444_10  = 17,  
   eAVEncH265VProfile_MainIntra_444_12  = 18,  
   eAVEncH265VProfile_MainIntra_444_16  = 19,  
   eAVEncH265VProfile_MainStill_420_8   = 20,  
   eAVEncH265VProfile_MainStill_444_8   = 21,  
   eAVEncH265VProfile_MainStill_444_16  = 22  
};  

Otherwise it works like H.264.

**Comment by zipswich** [comment]
@aarononeal Cannot believe that I missed this for so long (too many gibhub watches). 
Could you tell me where I can find CreateHEVC()?  I have just updated the samples, and I am looking at project PlayReady now, but unable to find it.

**Comment by oldnewthing** [comment]
`VideoEncodingProperties.CreateHevc`

**Comment by zipswich** [comment]
Thanks a lot, @oldnewthing  It works!
I misunderstood it thinking it was a part of the UWP sample.

**Comment by eduardoferrari** [comment]
Hello @zipswich, I saw your question here and I'm trying exactly the same thing, I have an UWP app and I'm trying to run a H.265 video from URL, but only the audio appears, can you please share your example with me? I tried to find were to use the `VideoEncodingProperties.CreateHevc` but, no success. Thank you so much
