### ISSUE TITLE
Simple Communication - Remote media failed on Video Chat

### ISSUE THREAD

**Issue by vino4all** [Microsoft/Windows-universal-samples#573]
I'm developing a video chat app from SimpleCommunication Video Chat sample code base. While trying to connect HoloLens with Windows 10 Laptop, call connected for 1 sec and I'm able to see the first frame, then immediately the control enters into '**RemoteVideo_MediaFailed**' method.

Help me to get a reliable video chat app. I'm planning to attach MRC effects to the captured video.

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. It appears to be a question about building a new app based on a sample. If you have a problem that can be demonstrated by the sample itself, please call that out. Otherwise, if the problem is with adapting the sample to your needs, you can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by zhuisa** [comment]
@vino4all hi! now I have the same problem with you. I cannot connect hololens with desktop using the Simple Communication demo. Can you tell me that how do you deal with? or some thought.
