### ISSUE TITLE
Sample available for a custom UWP UserDataAccount provider?

### ISSUE THREAD

**Issue by fubar-coder** [Microsoft/Windows-universal-samples#578]
I'd like to implement my own UserDataAccount provider, but I cannot find samples how to do so. It would also be nice to find an example where I can see the usage of the classes in the `Windows.ApplicationModel.UserDataAccounts.Provider` namespace.

**Comment by oldnewthing** [comment]
As noted in [the documentation](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.UserDataAccounts.Provider), being a UserDataAccount provider requires the **userDataAccountsProvider** restricted capability. As a general rule, this repo does not include samples for APIs that require restricted capabilities because those capabilities are not available to most developers.
