### ISSUE TITLE
the default Magnetometer Sensor can't be accessed by WinRT API

### ISSUE THREAD

**Issue by lvaptx4869** [Microsoft/Windows-universal-samples#594]
On the MSDN, Magnetometer have standard WinRT API [https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.magnetometer](url) . The reading claims that it can obtain the MagneticFieldX, MagneticFieldY, MagneticFieldZ. While compass gets HeadingMagneticNorth, HeadingTrueNorth. However, in the Sensor HID Class Driver page [https://msdn.microsoft.com/en-us/windows/hardware/drivers/hid/sensor-hid-class-driver](url) , mag is left out and there is no sample code for mag in this repo. I guess that  the WinRT API is defined, it's not implemented yet?

**Comment by oldnewthing** [comment]
The class is present and implemented. It's just that there's no sample.

**Comment by lvaptx4869** [comment]
thanks for your replying. However, I can't get access to the Mag. I just wonder what's the hid usage id for mag since the hid spec updated last year. mag is set to C2.

**Comment by oldnewthing** [comment]
Since this isn't a question about a sample, I'm going to defer to the Developer Support team.

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by lvaptx4869** [comment]
OK. Thanks, is there any plan to provide a sample for the mag? I will go the suggested website for specific help.

**Comment by oldnewthing** [comment]
I'll ask the feature team to consider it.
