### ISSUE TITLE
Geofence not triggering

### ISSUE THREAD

**Issue by thenecroscope** [Microsoft/Windows-universal-samples#602]
Hi, I'm testing the Geofence app using VS2017 and c#. I am unable to get the event to trigger using my device 950 (fast build: 15047) nor using routes on the emulator. The events just dont seem to trigger at all using foreground or background?

**Comment by mjbedford2017** [comment]
I am having the exact same issue. Did this ever get resolved? @thenecroscope did you ever get it working somehow? I am using the Geolocation sample as is (did not change any code) and the OnGeofenceStateChanged (line 186 in scenario 4 xaml.cs) as well as the OnGeofenceStatusChanged (line 173) do not fire. I have verified that statup is good, I enabled and confirmed access to location on the device, and that the events are registered. I have also tried on the emulator and on an actual W10M device. I also verified that I have setup a geofence and have tried many different settings (no dwell time on most to remove that as an issue). 

Can somebody please help with this?

Thanks!

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by Cheoljin** [comment]
This is from the feature team. I have tested this on latest builds, e.g., PC (Build 16299) with fake locations, moving laptop (17045), and RS3 WP. They work fine as designed.

(1) If you use phone emulator running on PC, the position information is NOT acquired by Satellite GPS but IP address or Wi-Fi in general, meaning that the position is stationary because your position of PC hardly changes. This does not cause passing the geofence boundary you specified.

We can set a fake location via a special too, but I assume that you have not used it in this case.

(2) If you use actual phone that has a GPS receiver, the phone location should change based on the phone location. But I wonder if the device moved far enough to get in and out of the geofence boundary you specified. 

For me to see those events on the phone, I selected menu 'foreground geofencing', Set to Here, set the radius 100 meters, and checked Single Use. I see 'Enter' event in this case. I expect that If you move in and out of the virtual geometrical boundary within Duration (if you set as a period), then you would see the Exit and Enter event accordingly. At least, you should see 'Remove' event when the Duration expires.
