### ISSUE TITLE
XamlCloudFontIntegration, where do the fonts come from?

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Windows-universal-samples#603]
I have been trying to find the documentation about where the fonts come from, because in the app only appears 'Neue Haas Grotesk Text Pro'. I thought it has to come from a source like: https://www.microsoft.com/typography/fonts/  but for instance it does not exist there so:

1.- Where is the source ?
2.- Is it possible to use an Uri to set the source?

Thank you

**Comment by PeterCon** [comment]
The fonts are coming from a Microsoft-owned service for serving fonts included in the Windows license accessible by Windows 10 devices. This sample just uses a few fonts; the intent of this sample wasn't to show all of the fonts that are available, but only to show that the mechanisms for downloading fonts from this service that were added into the DirectWrite platform are fully integrated into the XAML framework.

If you want a more-detailed look at the DirectWrite mechanisms and related APIs, you can take a look at the [DWriteTextLayoutCloudFont](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DWriteTextLayoutCloudFont) sample. Related to this are extensions to the APIs that we have added in the Windows 10 Creators Update that allow a DirectWrite app to use these mechanisms to access fonts from other font services. For a closer look at that, you can take a look at the [DirectWriteCustomFontSets](https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/DirectWriteCustomFontSets) sample that got published on GitHub last week.

But if what you're interested in is more information about the additional fonts, such as Neue Haas Grotesk Pro, that you may not see in your Windows 10 system by default, you can find some details in [this topic](https://answers.microsoft.com/en-us/windows/forum/windows_10-start/some-fonts-are-missing-after-upgrade/95839dfa-0df2-4bc0-875a-fd6b57e61fe4) in the Windows 10 community forum site.

**Comment by juanpaexpedite** [comment]
Thank you, now at least I have a list and a 'source' of the fonts. 

About other font services, yes, I read https://msdn.microsoft.com/en-us/library/windows/desktop/hh802480(v=vs.85).aspx about  'Some font services, such as Adobe Typekit'. I am a novice in that services I will try to test that one.

Is there any other one service to try? If I understand well, if I have that font service installed and I set the name, the font just works in the UWP app?. Would be possible create one by myself?

The reason of my questions is that I'm creating a great update in 'Universal Character Map' with a lot of new features, and in next releases I would like to master about all downloadable fonts and fonts services.

**Comment by PeterCon** [comment]
There are various online font services, most of them intended for use in Web sites using the CSS @font-face rule. (See [CSS Fonts Level 3](http://www.w3.org/TR/css-fonts-3/) for more on that.) These may or may not allow for native applications to access fonts.

Some font services, such as Adobe Typekit and Google Fonts, have APIs that apps (Web or native) can interact with. But note that those two examples have very different target audiences and business models: Google Fonts is geared mainly toward use on the Web, and most fonts are open-source fonts provided without any licensing fees. Typekit is geared to a large extent toward Adobe Creative Cloud users, and less than 10% of the fonts are available for free. The pricing model is significant particularly because it generally affects how the font data is handled --- whether there are mechanisms in place to secure it. In the case of Google fonts, the raw font files can be accessed directly with a URL, and it's not hard to discover those URLs. But with TypeKit, on the other hand, the data is pretty tightly controlled. As a result, it's fairly straightforward to use a font from the Google Font service (as well as the Windows service) with the DirectWrite APIs in Windows 10 Creators Update, but it would be harder, if even possible, to access the fonts from Typekit directly with your own code.

Adobe Typekit and Monotype SkyFonts are services that have native sync client utilities that can be used to sync fonts from those services onto a Windows PC and use them like any normally-installed font. These sync clients don't actually install the fonts in the usual sense. Rather, they load the fonts into GDI after you have logged onto the system and the clients are started up. So, you can't use the fonts if the Typekit or SkyFonts client isn't running. The MSDN page you referred to mentions these client utilities; because of the way they interact with GDI, fonts that they load previously weren't visible to DirectWrite apps. But in the Anniversary Update, we did work so that DWrite is aware of fonts that utilities such as these load into GDI.

If you want to access fonts from the Windows service in your app, and the app calls DirectWrite APIs directly, then you can use IDWriteFactory3::GetSystemFontSet or use IDWriteFactory3::GetSystemFontCollection passing includeDownloadableFonts = TRUE, and the results will include fonts that are in the Windows service as well as those that are installed. You can determine the current locality state using IDWriteFontFaceReference::GetLocality, IDWriteFont3::GetLocality, or IDWriteFontFamily1::GetFontLocality.

If your app uses XAML, then you can just reference any of the fonts in the Windows service, the same way as is done in this sample. If the fonts are not cached locally, text will initially display using fallback fonts, but then the XAML text control will automatically refresh when DirectWrite has finished downloading the font.

If you want to use fonts from other online sources in your app, and you call DirectWrite APIs directly, then the new APIs in the Windows 10 Creators Update will be helpful, and you should check out the Custom Font Sets sample I mentioned earlier. But if your app uses XAML or HTML, then there currently isn't a way to use them directly as is done in this sample. Instead, if you have a Web view, you can write @font-face rules to reference font files available on the Web. (If you'd like to be able to use fonts from other services directly in intrinsic XAML text controls, we're interested in hearing about that.)

I hope this helps.

**Comment by juanpaexpedite** [comment]
Really appreciated for the detailed information, I will do my best with that information. 

If I understand well, In case I want to show in a native XAML app text from a font face from some web oriented font services, an option is using a webview where I should use that css rule (hopefully I was able to create a transparent webview). 

I will try also to use 'src: url(http://another.example.com/fonts/simple.woff);' and check how it behaviour.

Thank you for all the details, I will try all the possibilities.

**Comment by PeterCon** [comment]
Yes, you understand that correctly. The webview should support URLs pointing to .ttf, .woff or .woff2 files.
