### ISSUE TITLE
SimpleCommunication problem when using MediaPlayer without XAML/MediaElement

### ISSUE THREAD

**Issue by philfleck** [Microsoft/Windows-universal-samples#641]
I tried the [example](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SimpleCommunication) and it works so far. I want to use it in an application without XAML. 

In my application (without XAML) i can start capturing+streaming (stsp) and i can replay it within the XAML-sample. When I try to replay it in my application (without XAML) i get the error "unsupported stream". As used in the sample, i am using the [MediaExtensionManager](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaextensionmanager) to register the StspSchemeHandler. But again, i ran into the unsupported stream error. All i did so far is to add the [CaptureDevice.cs](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SimpleCommunication/cs/CaptureDevice.cs) class, the [common-library](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SimpleCommunication/common/MediaExtensions/Microsoft.Samples.SimpleCommunication) and a wrapper to a new project. For replay i replaced the MediaElement with the [MediaPlayer](https://msdn.microsoft.com/en-us/library/system.windows.media.mediaplayer(v=vs.110).aspx) class. 

To register the StspSchemeHandler I use something like this:
`mediaext_mgr = new Windows.Media.MediaExtensionManager();`
`mediaext_mgr.RegisterSchemeHandler("Microsoft.Samples.SimpleCommunication.StspSchemeHandler", "stsp:");`

I also tried to a PropertySet to the to the RegisterSchemeHandler call, but i am not exactly which values to pass - based on the hint of this [MSDN-post](https://social.msdn.microsoft.com/Forums/en-US/a74aa261-31eb-4bfb-976c-e30d84889581/get-pointer-to-the-imfmediasource-from-a-imfmediaengine?forum=winappswithnativecode).  

I would appreciate any help.

**Comment by aarononeal** [comment]
MediaElement and MediaPlayer use the same internal media engine so this is most likely an issue that occurred when forking the sample. If you prepare a test project and link here we may be able to verify whether or not this is a platform issue.

Otherwise, you can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
