### ISSUE TITLE
WebAuthenticationBroker sample is not work

### ISSUE THREAD

**Issue by poumason** [Microsoft/Windows-universal-samples#642]
I reference the [https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebAuthenticationBroker](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebAuthenticationBroker) sample to implement Google OAuth.

But I always got exception:
```
The process terminated unexpectedly. (Exception from HRESULT: 0x8007042B)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebAuthentication.Scenario4_Google.<Launch_Click>d__3.MoveNext()
```
But it work on the Windows 10 14393.

**Comment by saurabha5** [comment]
@poumason, which OS version you are on?

**Comment by poumason** [comment]
I use 15063.

**Comment by jgilm** [comment]
I have a customer that gets this on his computer, but all of his other work colleagues the same version of the application works correctly. 
The exception happens when calling `WebAuthenticationBroker.AuthenticateAsync` as below

```
 var result = await WebAuthenticationBroker.AuthenticateAsync(
                    WebAuthenticationOptions.None,
                    authCodeUri,
                    callbackUri);
```
The callbackUri is **not ** a `ms-app://` type of Uri, but a custom one. The current version of software works for a vast majority of our users, but a couple are running into this issue.

[This page](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/7605fcab-8318-4dae-a873-441bd0685863/webauthenticationbrokerauthenticateasync-throws-exception-on-the-desktop?forum=winappswithcsharp) has a couple of scenarios including "corrupt user profile" or "misconfigured permissions on the Internet Explorer's Temporary Internet Files folder". I don't know yet if either of these are the issue with my customer, just thought I'd throw it out there.

**Comment by jgilm** [comment]
Anybody have any ideas? I am having other customers that are running into this issue, but there is no other I have not found any additional information. The scenarios I've listed above did not seem to help previous customers running into this issue.

**Comment by poumason** [comment]
I write the [OAuth dialog control ](https://github.com/poumason/DotblogsSampleCode/blob/master/DotblogsSampleCode/13-AppWithOAuth/AppWithOAuth/UI/OAuthDialog.cs) and [XAML](https://github.com/poumason/DotblogsSampleCode/blob/master/DotblogsSampleCode/13-AppWithOAuth/AppWithOAuth/Themes/Generic.xaml) to solve the issue.

**Comment by oldnewthing** [comment]
I think this is the same as issue #643

**Comment by jgilm** [comment]
Nope, not the same issue. I am not using Google OAuth and am not using a `?` in the callback uri.

**Comment by oldnewthing** [comment]
Okay, I will ask the feature team to investigate.

**Comment by EmilAlipiev** [comment]
Hi please find answer on this SO thread.  https://stackoverflow.com/questions/50242480/google-calendar-api-for-uwp-windows-10-application/50789038#50789038

you must create an Ios Client Id in the backend and you should use returnurl as `urn:ietf:wg:oauth:2.0:oob:auto`
