### ISSUE TITLE
Speech recognition without constraints.

### ISSUE THREAD

**Issue by fefespn** [Microsoft/Windows-universal-samples#666]
I am trying to speech recognition without any constraints.
here: 
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/HolographicVoiceInput/cpp/HolographicVoiceInputMain.cpp#L213-L215
they have constraints.
I tried to remove these line, but the code does not recognize the speech at all! 
does the handler stay the same handler, ContinuousRecognitionSession->ResultGenerated  ?! 
if not, wich handler I should change ?! 
or maybe my problem isn't the handler !? 
thank you

**Comment by anpilley** [comment]
If you're trying to get speech dictation (unconstrained speech), you're going to want to look at the example in the regular c++/XAML app:
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SpeechRecognitionAndSynthesis/cpp/Scenario_ContinuousDictation.xaml.cpp#L100-L101

This shows how to initialize dictation with a topic constraint, which will allow free-form speech to text recognition instead of keyword recognition.

The Hololens samples don't include this because rendering text in the hololens device is beyond the scope of the sample.

**Comment by fefespn** [comment]
than you.
I did all what you say before.
my problem is that the handlers did not start when I start to speek.
not Hypothesis nor resultGenerated.

**Comment by anpilley** [comment]
Okay, first up, make sure you've got the InternetClient permission requested in your appx manifest, it's required for dictation to initialize.

Second, register for the ContinuousRecognitionSession->Completed event handler. Likely, what you're seeing is that while Dictation starts up, it times out relatively quickly (Default, I believe, is 5 seconds of silence.) Continuous Dictation isn't able to run indefinitely, because it utilizes an internet connection to access external dictation services.

You can increase various timeouts by modifying the SpeechRecognizer::Timeouts struct. Details on the various properties are available here: https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognizertimeouts

**Comment by fefespn** [comment]
thank you !! it works now !! the  InternetClient permission was missed 👍

**Comment by anpilley** [comment]
Glad to hear that, good luck!
