### ISSUE TITLE
AudioGraph Waveform Example

### ISSUE THREAD

**Issue by tjscience** [Microsoft/Windows-universal-samples#669]
It would be really helpful to see an example of a drawn waveform using data obtained from AudioGraph.

**Comment by tjscience** [comment]
Does anyone know of any example of this??

**Comment by oldnewthing** [comment]
I created an item on the feature team's backlog.

**Comment by aklemets** [comment]
Graph drawing seems unrelated to the AudioGraph API sample. The purpose of the API sample is to illustrate how the AudioGraph API is used. There are multiple ways to draw graphs. Excel can be used, for example.
For audio data I have been using an open source program called Audacity to draw waveforms. It is better than Excel for this purpose, because you can select parts of the waveform and listen to it. 
When using AudioGraph one can use an AudioFrameOutputNode to save the data to a .wav file and then open the resulting .wav file in Audacity. It will draw the graph for you.

**Comment by tjscience** [comment]
Ok then... How about an example of writing the data to a wav file?

**Comment by oldnewthing** [comment]
[Scenario 2 shows how to do this](https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/AudioCreation/cs/AudioCreation/Scenario2_DeviceCapture.xaml.cs).

**Comment by tjscience** [comment]
That example does not show how to obtain the sound data necessary to draw a waveform. It simply saves the file as a wav. I, and I'm sure other people, are after an example to get to the underlying data.

**Comment by oldnewthing** [comment]
Okay, sorry. I'm not an audio person. But the WAV file format is well-documented.

**Comment by BenPYeh** [comment]
@tjscience if you want to get to the underlying raw data, you may adapt the code in this doc https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs#audio-frame-input-node, specifically look at the GenerateAudioData() function, and use it to read the data instead of writing to it.
