### ISSUE TITLE
Can you provide an actual VoIP example?

### ISSUE THREAD

**Issue by manjia** [Microsoft/Windows-universal-samples#684]
The VoIP example provided is NOT a VoIP for 2 main reasons:

- first: according to the example the voice is not supposed to traver over IP adresses but over microsoft's obscure protocol tied to the microsoft accounts ecosystem
- second: the provided example doesn't actually even do that, it just loopsback the audio form the microphone to the spekers of the same machine, no explanation on how to extend this on 2 machines is provided anywhere

can you please provide an actual VoIP example?

**Comment by oldnewthing** [comment]
The purpose of the VoIP sample is to show what a VoIP client needs to do in order to integrate with the platform. There is a lot of stuff a VoIP company needs to do that is not related to the platform such as provisioning a bunch of servers in a data center somewhere, amassing subscribers, and looking them up in a database. That is beyond the scope of the sample, so it is simulated with loopback. How you connect to your data center, find other customers of your service, and connect the two endpoints is your company's business logic.

**Comment by manjia** [comment]
Then the sample name is VERY misleading, it should be called "Voice chat client" or something like that, VoIP means "voice over internet protocol" and this sample does not implement anything like that. 
A VoIP sample is supposed of course to implement some kind of connection between at least 2 peers (and perhaps a test server to try out the technology performence if the connection is not direct).
I wonder how many people wasted time in downloading and running this sample just to find out it is not related with VoIP at all, please be honest and don't claim "here's the moon" when you actually own a stone.
