### ISSUE TITLE
If I set the `CommandManager.IsEnabled = false;` , then the Bluetooth headset can't get metadata.

### ISSUE THREAD

**Issue by poumason** [Microsoft/Windows-universal-samples#727]
https://github.com/Microsoft/Windows-universal-samples/blob/85b2522a06f3622cc985ea95bab068a01a816d70/Samples/SystemMediaTransportControls/cs/Scenario1.xaml.cs#L746

If I set the `CommandManager.IsEnabled = false;` , then the Bluetooth headset can't get metadata.
I already try use SystemMediaTransportControlsDisplayUpdater to update, and it still be not work.

How can I solved the it?
Thank you.

**Comment by aarononeal** [comment]
Why do you want to disable CommandManager?

If you disable CommandManager you have to do everything manually. You can't just use the display updater, you must also enable SystemMediaTransport controls and subscribe to button presses.

But there are very few cases where you need to do that instead of just updating through CommandManager.

Closing as this is not a sample issue.
