### ISSUE TITLE
Projects can not be loaded in Visual Studio  2017 -  15.3.4

### ISSUE THREAD

**Issue by verosys** [Microsoft/Windows-universal-samples#729]
I just upgraded Visual Studio 2017 to version 15.3.4. After the upgrade I downloaded the latest version of the repository and now it can not open the DeviceEnumerationAndPairing and SmsSendAndReceiveProjects. In both cases VS started to convert the solution. After the conversion when the solution is opened, VS states that the projects are incompatible. With the old VS 2017 the projects were loaded after conversion

**Comment by oldnewthing** [comment]
Can you be specific which branch you downloaded and which language (C++, C#, or JS) is demonstrating the problem?

**Comment by oldnewthing** [comment]
I cannot reproduce the problem. I installed Visual Studio Community 2017, grabbed the `master` branch, and was able to load and build the following projects:

* DeviceEnumerationAndPairing, C++, Debug x86. Needed to build twice because of a missing build order dependency between the background task and the foreground app. I'll fix that.
* DeviceEnumerationAndPairing, C#, Debug x86. Built with no issues.
* DeviceEnumerationAndPairing, JS, Debug, Any CPU. Built with no issues.
