### ISSUE TITLE
Bluetooth Low Energy sample - crashes upon select HumanInterfaceDevice service

### ISSUE THREAD

**Issue by agomes100** [Microsoft/Windows-universal-samples#734]
Hi, 

I noticed that the Bluetooth Low Energy sample crashes upon selecting HumanInterfaceDevice service.

I've tested it with a Surface Dial and a Microsoft Surface Keyboard, both of them crash.

I'm working toward reading the clicks and rotations of a Microsoft Surface Dial.

Appreciated, 
Alexandre Siqueira.

**Comment by oldnewthing** [comment]
Can you be specific which branch you are working from, and what OS you are testing on?

**Comment by agomes100** [comment]
Hi!
I'm running the code from the master branch, on a Windows 10 machine with the Creators update. 

Let me know if I can be more specific and help in any way. 

Appreciated, 
Alexandre Siqueira.

**Comment by oldnewthing** [comment]
Thanks. The feature team confirmed that this is a bug in the sample. In `Scenario2_Client.ServiceList_SelectionChanged`, there is a missing else clause.

    if (result.Status == GattCommunicationStatus.Success)
    {
        characteristics = result.Characteristics;
    }
    // ADD THE FOLLOWING
    else
    {
        // On error, act as if there are no characteristics.
        characteristics = New List<GattCharacteristics>();
    }

Now the sample won't crash, but you still won't be able to access HID services via Bluetooth. This is by design. To access HID data, use the HID APIs.

The fix will appear in the next refresh. Thanks for reporting the issue.
