### ISSUE TITLE
barcode scanner 

### ISSUE THREAD

**Issue by Mcavender30269** [Microsoft/Windows-universal-samples#757]
in solution  explorer says "update required" right click  directs to this site which has nothing https://www.msn.com/?ocid=NEFLS000

**Comment by oldnewthing** [comment]
This is probably due to the change from 15063 to 16299 two days ago. All of the samples the `master` branch require the 15063 SDK. If Visual Studio can't obtain the update automatically, you can download and install it manually. You can install specific versions of the SDK from [this page](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive).
