### ISSUE TITLE
HolographicMRCapture C++ Exception

### ISSUE THREAD

**Issue by EduardsBrown** [Microsoft/Windows-universal-samples#765]
Hi,

I am trying to run the C++ HolographicMRCapture project, but I am getting an exception inside DeviceResources.cpp line 400:
![image](https://user-images.githubusercontent.com/9280894/32047816-13add8c4-ba3f-11e7-8c36-0c2145acba12.png)

The exception is:
![image](https://user-images.githubusercontent.com/9280894/32047863-37d01a82-ba3f-11e7-9c77-9adb24c982c4.png)

I am running this inside HoloLens emulator version 10.0.14393.1358

**Comment by EduardsBrown** [comment]
I've tested the project on HoloLens Device and it works, but the emulator doesn't.

**Comment by oldnewthing** [comment]
I'll ask the holographic team to look into this.

**Comment by brunovollmer** [comment]
Did you found a solution to this problem?

**Comment by oldnewthing** [comment]
The feature team tells me that the HoloLens emulator differs from a real device in a number of ways, and the sample is tripping over those differences.

* The D3D device is different, which is why the sample can't create the vertex shader. This is a bug in the sample. The feature team is investigating how to fix it.
* The emulator doesn't have a camera, so none of the camera features will work. This is a limitation of the emulator.

Since this sample relies on the camera, it won't work on the emulator because the emulator doesn't have a camera.

**Comment by oldnewthing** [comment]
A fix for the sample is coming in the next update. The sample will avoid using features that are not available in the emulator.
