### ISSUE TITLE
Microsoft Life-Cam 3000 HD does not support video profiles

### ISSUE THREAD

**Issue by v-liujxu** [Microsoft/Windows-universal-samples#799]
I run the sample code of [CameraProfile](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraProfile) on Raspberry Pi3 with windows iot core 17035.But it can not get profiles because the result of _MediaCapture.IsVideoProfileSupported(device.Id)_ is false.

Microsoft Life-Cam 3000 HD is official recommended in [Hardware compatibility list](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist).

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by LPAMNijoel** [comment]
Thank you! @oldnewthing and @v-liujxu!

**Comment by oldnewthing** [comment]
Here's what the feature team says:

Camera Profiles are not mandatory for camera manufacturers.  It’s only needed when the camera exposes multiple combination of pins/media types which are mutually incompatible.  For example, if the camera exposes a photo pin and a video pin, but cannot capture photo at the highest resolution while simultaneously stream at the highest resolution of the video pin.
 
For USB based cameras, since there’s typically only one pin, profiles are not needed.  And in the Fall Creators Update and earlier, profiles were not available for USB Video Class based cameras (no way for IHV/OEMs to publish profiles for UVC based cameras).
 
We are working on adding support since there will be IR+RGB combo UVC cameras with constraints on what resolution the individual streams can run at when both are turned on.  These will publish Face Authentication profiles for Windows Hello consumption.
 
Developers who want to test their profile logic should target MIPI based cameras that expose multiple pins. Examples of these cameras are various QC SOC based devices (such as Lumia 950/950XL, HP Elite X3) or Intel MIPI based systems (such as Surface Pro/Surface Pro 4/Surface Book/Surface Laptop).
 
For Surface Pro 4/Surface Book 1, the latest 4731 camera drivers publish profiles (the factory image drivers do not).

**Comment by v-liujxu** [comment]
Thank you.
