### ISSUE TITLE
SpatialCoordinateSystem and matrix4x4

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/Windows-universal-samples#800]
I can't find anything about what "SpatialCoordinateSystem" is on the document page. Does anyone know what the 4by4 matrix returned by the method "TryGetTransformTo" is? Is the matrix following the right hand convention or left hand?  Does it support post concatenation or pre concatenation for matrix multiplications? what is the x,y,z vector of the wold space... Nothing..... Absolutely nothing. The only thing I know about this matrix is it is row majored and it's in meters.

**Comment by oldnewthing** [comment]
This is documented in MSDN under [Spatial Coordinate Systems](https://developer.microsoft.com/en-us/windows/mixed-reality/coordinate_systems#spatial_coordinate_systems).

**Comment by xueyuancao0218** [comment]
After we create a spatial anchor, we could get its position 4x4 matrix. As we all know, the coordinate system of our machine is relating to itself. (For instance, hololens.) If we want to change the current coordinate system to the spatial anchor, we could use a method named: CreateStationaryFrameOfReferenceAtCurrentLocation() from SpatialAnchor. 

However, in order to use this method, we need to have a vector3 as its parameter. How do we transform a position 4x4 matrix to a vector3? I have searched a lot, but I did not find anything about this content. Is it possible that anyone could give me a little help? Any suggestion would be appreciated!
