### ISSUE TITLE
Projection: can't get to title bar buttons after starting projection when in full screen

### ISSUE THREAD

**Issue by francisrath** [Microsoft/Windows-universal-samples#820]
I have a problem in an application I am developing, and I tried to see if the same issue applies to the Projection sample in this project, and it does.

### Problem
The window title bar buttons (minimize, restore, close) should always appear when mouse pointer is at top of the screen in full screen, but they do not after starting projection, unless the window looses and regains focus.

### Steps to reproduce
Open `Projection.sln` and edit `App.xaml.cs` to add `ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.FullScreen;` just before `Window.Current.Activate();` in `protected override void OnLaunched(LaunchActivatedEventArgs e)`

Start the application, click `Start projecting` to show projected view on secondary screen. Move mouse pointer to top of screen to reveal title bar buttons . Nothing appears.
Click for example `Win` button on keyboard twice to loose+regain focus to window. It wil now work properly.

### Expectation
Mouse to top of screen should always reveal title bar buttons.

Any feedback on workarounds or permanent fixes would be very welcome 😄

**Comment by oldnewthing** [comment]
This appears to be a platform issue rather than a bug in the sample. I've asked the samples team to look at it, but you will probably get a better response if you open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by oldnewthing** [comment]
The samples team confirms that the sample is doing everything right; the behavior is in the platform. Projection is not quite the same as full screen. Another difference you may discover is that edge swipe gestures are not active while projecting.
