### ISSUE TITLE
Issues with IoT-Gpio sample

### ISSUE THREAD

**Issue by jordanrh1** [Microsoft/Windows-universal-samples#920]
- Missing `<DeviceCapability Name="lowLevel" />`
 - Race condition in listen scenario when you click 'Stop'. Event handler crashes when it tries to reference deleted pin.
 - Pin numbers are hardcoded. Should be configurable from UI
 - Poor error handling. App just crashes when something goes wrong. Should display errors in the UI.
 - Uses dispatcher timer timer to toggle pin. This code does not need to run on the UI thread. Should use a timer that does not run on the UI thread.

**Comment by oldnewthing** [comment]
Some of the issues are valid, but others are by design.

* Pin numbers are hard-coded because this is a sample, not a functional test. You would choose the pins appropriate for your device.
* What types of errors are you referring to? If it's a configuration error, then crashing is by design. IoT considers it a developer error to deploy to an improperly configured device.
* You are welcome to use a different kind of timer if you want. But dispatcher timers are valid too.

**Comment by oldnewthing** [comment]
You can reopen if the error is something other than a system configuration error.
