### ISSUE TITLE
BluetoothLE sample - deviceWatcher does not raise Added event after EnumerationCompleted

### ISSUE THREAD

**Issue by aprobinda** [Microsoft/Windows-universal-samples#932]
I could be wrong, but I think that behavior of `deviceWatcher` in 
[BluetoothLE sample - Scenario1_Discovery.xaml.cs](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BluetoothLE/cs/Scenario2_Client.xaml.cs)
is not what I expect after reading this:
> The DeviceWatcher raises an EnumerationCompleted event when the initial enumeration is complete, and continues to raise events if a device is added, updated, or removed.

https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher#remarks

What I see is that if I power on a new device after an `EnumerationCompleted`, this device will not trigger the `Added` event handler. In other words, `DeviceWatcher` **does not continue** to raise events if a device is added.  So, I have to add to `private async void DeviceWatcher_EnumerationCompleted` these lines:
```
// quick fix: repeat the discovery process, so the KnownDevices list keeps refreshing after Enumeration has completed:
StopBleDeviceWatcher();
StartBleDeviceWatcher();
```

**Comment by mtbeaver** [comment]
This is expected behavior, as we explicitly limit the discovery time via this API.  The Windows.Devices.Enumeration query for Bluetooth devices, depending on the baseband, will either perform a series of inquiry cycles, or perform active scanning at 100% duty cycle for approximately 30s.  After the enumeration is completed, these activities will be cancelled, as this has both serious power drain on the system, and will interfere with any other ongoing Bluetooth activities, such as audio streaming and HID usage.

Though the active discovery of the device has stopped at this point, if the device is found via other means, such as a directed advertisement through the whitelist, or an Advertisement Watcher, the results are still delivered to the enumeration API.

An application should not Stop/Start the watcher as you are doing here. This will, as I mentioned above, severely limit the available radio resources, preventing Audio, HID and WiFi (depending on the hardware) from working well on the system.  If you need a prolonged query to monitor for the presence of LE devices, I would recommend the [Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher) API.  We have a [sample](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BluetoothAdvertisement/cs/Scenario1_Watcher.xaml.cs) available for this API as well.
