### ISSUE TITLE
PDF header not visible on some pdf file

### ISSUE THREAD

**Issue by tatvaanant** [Microsoft/Windows-universal-samples#934]
I am having problem while render PDF file using  Windows.Data.Pdf.PdfDocument 
in some file PDF header is not displaying and the same issue happen when you open PDF file using Microsoft Edge browser to however using other third party application it is working fine.

[SamplePDF Header Issue.pdf](https://github.com/Microsoft/Windows-universal-samples/files/2154693/SamplePDF.Header.Issue.pdf)

**Comment by oldnewthing** [comment]
Since Edge has the same problem, this sounds like an issue with the platform, not with the sample. 

You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
