### ISSUE TITLE
ProjectionManager.StartProjectingAsync get “0x80070005 AcessDenied” 

### ISSUE THREAD

**Issue by liangming2003** [Microsoft/Windows-universal-samples#974]
I encountered same problem with following issue, do you know how to resolve this?

//github.com/Microsoft/Windows-universal-samples/issues/548

The exmple code I use.
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Projection/cs

Test Enviroment:
VS 2017 + Windows SDK 10.1.15063  + Win 10

**Comment by oldnewthing** [comment]
The feature team explains that `ProjectionManager.StartProjectionAsync` requires that the app initiating the projection to be active (in the foreground) at the time the call to `StartProjectionAsync` occurs. If that is not the case, then the `StartProjectingAsync` call will fail. This is called out [in the documentation for `StartProjectionAsync`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.projectionmanager.startprojectingasync#Windows_UI_ViewManagement_ProjectionManager_StartProjectingAsync_System_Int32_System_Int32_for). If you are debugging the app, this error occurs more often because the debugger will take foreground away from the app when you step through the code. The way to work around this is to set the breakpoint on the line *after* the `StartProjectionAsync`, so that the call is made while the app still has foreground.
